// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HMI_RX_CONTROLS.proto

#include "HMI_RX_CONTROLS.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR Waypoint::Waypoint(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.lat_)*/0
  , /*decltype(_impl_.lon_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct WaypointDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WaypointDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~WaypointDefaultTypeInternal() {}
  union {
    Waypoint _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WaypointDefaultTypeInternal _Waypoint_default_instance_;
PROTOBUF_CONSTEXPR Navigation::Navigation(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.waypoints_)*/{}
  , /*decltype(_impl_.current_lat_)*/0
  , /*decltype(_impl_.current_lon_)*/0
  , /*decltype(_impl_.heading_deg_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct NavigationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NavigationDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~NavigationDefaultTypeInternal() {}
  union {
    Navigation _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NavigationDefaultTypeInternal _Navigation_default_instance_;
static ::_pb::Metadata file_level_metadata_HMI_5fRX_5fCONTROLS_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_HMI_5fRX_5fCONTROLS_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_HMI_5fRX_5fCONTROLS_2eproto = nullptr;

const uint32_t TableStruct_HMI_5fRX_5fCONTROLS_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Waypoint, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Waypoint, _impl_.lat_),
  PROTOBUF_FIELD_OFFSET(::Waypoint, _impl_.lon_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Navigation, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Navigation, _impl_.current_lat_),
  PROTOBUF_FIELD_OFFSET(::Navigation, _impl_.current_lon_),
  PROTOBUF_FIELD_OFFSET(::Navigation, _impl_.heading_deg_),
  PROTOBUF_FIELD_OFFSET(::Navigation, _impl_.waypoints_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Waypoint)},
  { 8, -1, -1, sizeof(::Navigation)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_Waypoint_default_instance_._instance,
  &::_Navigation_default_instance_._instance,
};

const char descriptor_table_protodef_HMI_5fRX_5fCONTROLS_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025HMI_RX_CONTROLS.proto\"$\n\010Waypoint\022\013\n\003l"
  "at\030\001 \001(\002\022\013\n\003lon\030\002 \001(\002\"i\n\nNavigation\022\023\n\013c"
  "urrent_lat\030\001 \001(\002\022\023\n\013current_lon\030\002 \001(\002\022\023\n"
  "\013heading_deg\030\003 \001(\002\022\034\n\twaypoints\030\004 \003(\0132\t."
  "Waypointb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_HMI_5fRX_5fCONTROLS_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_HMI_5fRX_5fCONTROLS_2eproto = {
    false, false, 176, descriptor_table_protodef_HMI_5fRX_5fCONTROLS_2eproto,
    "HMI_RX_CONTROLS.proto",
    &descriptor_table_HMI_5fRX_5fCONTROLS_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_HMI_5fRX_5fCONTROLS_2eproto::offsets,
    file_level_metadata_HMI_5fRX_5fCONTROLS_2eproto, file_level_enum_descriptors_HMI_5fRX_5fCONTROLS_2eproto,
    file_level_service_descriptors_HMI_5fRX_5fCONTROLS_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_HMI_5fRX_5fCONTROLS_2eproto_getter() {
  return &descriptor_table_HMI_5fRX_5fCONTROLS_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_HMI_5fRX_5fCONTROLS_2eproto(&descriptor_table_HMI_5fRX_5fCONTROLS_2eproto);

// ===================================================================

class Waypoint::_Internal {
 public:
};

Waypoint::Waypoint(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Waypoint)
}
Waypoint::Waypoint(const Waypoint& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Waypoint* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.lat_){}
    , decltype(_impl_.lon_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.lat_, &from._impl_.lat_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.lon_) -
    reinterpret_cast<char*>(&_impl_.lat_)) + sizeof(_impl_.lon_));
  // @@protoc_insertion_point(copy_constructor:Waypoint)
}

inline void Waypoint::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.lat_){0}
    , decltype(_impl_.lon_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Waypoint::~Waypoint() {
  // @@protoc_insertion_point(destructor:Waypoint)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Waypoint::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Waypoint::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Waypoint::Clear() {
// @@protoc_insertion_point(message_clear_start:Waypoint)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.lat_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.lon_) -
      reinterpret_cast<char*>(&_impl_.lat_)) + sizeof(_impl_.lon_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Waypoint::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float lat = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _impl_.lat_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float lon = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.lon_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Waypoint::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Waypoint)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float lat = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_lat = this->_internal_lat();
  uint32_t raw_lat;
  memcpy(&raw_lat, &tmp_lat, sizeof(tmp_lat));
  if (raw_lat != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_lat(), target);
  }

  // float lon = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_lon = this->_internal_lon();
  uint32_t raw_lon;
  memcpy(&raw_lon, &tmp_lon, sizeof(tmp_lon));
  if (raw_lon != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_lon(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Waypoint)
  return target;
}

size_t Waypoint::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Waypoint)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float lat = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_lat = this->_internal_lat();
  uint32_t raw_lat;
  memcpy(&raw_lat, &tmp_lat, sizeof(tmp_lat));
  if (raw_lat != 0) {
    total_size += 1 + 4;
  }

  // float lon = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_lon = this->_internal_lon();
  uint32_t raw_lon;
  memcpy(&raw_lon, &tmp_lon, sizeof(tmp_lon));
  if (raw_lon != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Waypoint::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Waypoint::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Waypoint::GetClassData() const { return &_class_data_; }


void Waypoint::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Waypoint*>(&to_msg);
  auto& from = static_cast<const Waypoint&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Waypoint)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_lat = from._internal_lat();
  uint32_t raw_lat;
  memcpy(&raw_lat, &tmp_lat, sizeof(tmp_lat));
  if (raw_lat != 0) {
    _this->_internal_set_lat(from._internal_lat());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_lon = from._internal_lon();
  uint32_t raw_lon;
  memcpy(&raw_lon, &tmp_lon, sizeof(tmp_lon));
  if (raw_lon != 0) {
    _this->_internal_set_lon(from._internal_lon());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Waypoint::CopyFrom(const Waypoint& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Waypoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Waypoint::IsInitialized() const {
  return true;
}

void Waypoint::InternalSwap(Waypoint* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Waypoint, _impl_.lon_)
      + sizeof(Waypoint::_impl_.lon_)
      - PROTOBUF_FIELD_OFFSET(Waypoint, _impl_.lat_)>(
          reinterpret_cast<char*>(&_impl_.lat_),
          reinterpret_cast<char*>(&other->_impl_.lat_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Waypoint::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_HMI_5fRX_5fCONTROLS_2eproto_getter, &descriptor_table_HMI_5fRX_5fCONTROLS_2eproto_once,
      file_level_metadata_HMI_5fRX_5fCONTROLS_2eproto[0]);
}

// ===================================================================

class Navigation::_Internal {
 public:
};

Navigation::Navigation(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Navigation)
}
Navigation::Navigation(const Navigation& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Navigation* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.waypoints_){from._impl_.waypoints_}
    , decltype(_impl_.current_lat_){}
    , decltype(_impl_.current_lon_){}
    , decltype(_impl_.heading_deg_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.current_lat_, &from._impl_.current_lat_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.heading_deg_) -
    reinterpret_cast<char*>(&_impl_.current_lat_)) + sizeof(_impl_.heading_deg_));
  // @@protoc_insertion_point(copy_constructor:Navigation)
}

inline void Navigation::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.waypoints_){arena}
    , decltype(_impl_.current_lat_){0}
    , decltype(_impl_.current_lon_){0}
    , decltype(_impl_.heading_deg_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Navigation::~Navigation() {
  // @@protoc_insertion_point(destructor:Navigation)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Navigation::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.waypoints_.~RepeatedPtrField();
}

void Navigation::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Navigation::Clear() {
// @@protoc_insertion_point(message_clear_start:Navigation)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.waypoints_.Clear();
  ::memset(&_impl_.current_lat_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.heading_deg_) -
      reinterpret_cast<char*>(&_impl_.current_lat_)) + sizeof(_impl_.heading_deg_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Navigation::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float current_lat = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _impl_.current_lat_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float current_lon = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.current_lon_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float heading_deg = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          _impl_.heading_deg_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // repeated .Waypoint waypoints = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_waypoints(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Navigation::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Navigation)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float current_lat = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_current_lat = this->_internal_current_lat();
  uint32_t raw_current_lat;
  memcpy(&raw_current_lat, &tmp_current_lat, sizeof(tmp_current_lat));
  if (raw_current_lat != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_current_lat(), target);
  }

  // float current_lon = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_current_lon = this->_internal_current_lon();
  uint32_t raw_current_lon;
  memcpy(&raw_current_lon, &tmp_current_lon, sizeof(tmp_current_lon));
  if (raw_current_lon != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_current_lon(), target);
  }

  // float heading_deg = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_heading_deg = this->_internal_heading_deg();
  uint32_t raw_heading_deg;
  memcpy(&raw_heading_deg, &tmp_heading_deg, sizeof(tmp_heading_deg));
  if (raw_heading_deg != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(3, this->_internal_heading_deg(), target);
  }

  // repeated .Waypoint waypoints = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_waypoints_size()); i < n; i++) {
    const auto& repfield = this->_internal_waypoints(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Navigation)
  return target;
}

size_t Navigation::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Navigation)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Waypoint waypoints = 4;
  total_size += 1UL * this->_internal_waypoints_size();
  for (const auto& msg : this->_impl_.waypoints_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // float current_lat = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_current_lat = this->_internal_current_lat();
  uint32_t raw_current_lat;
  memcpy(&raw_current_lat, &tmp_current_lat, sizeof(tmp_current_lat));
  if (raw_current_lat != 0) {
    total_size += 1 + 4;
  }

  // float current_lon = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_current_lon = this->_internal_current_lon();
  uint32_t raw_current_lon;
  memcpy(&raw_current_lon, &tmp_current_lon, sizeof(tmp_current_lon));
  if (raw_current_lon != 0) {
    total_size += 1 + 4;
  }

  // float heading_deg = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_heading_deg = this->_internal_heading_deg();
  uint32_t raw_heading_deg;
  memcpy(&raw_heading_deg, &tmp_heading_deg, sizeof(tmp_heading_deg));
  if (raw_heading_deg != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Navigation::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Navigation::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Navigation::GetClassData() const { return &_class_data_; }


void Navigation::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Navigation*>(&to_msg);
  auto& from = static_cast<const Navigation&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Navigation)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.waypoints_.MergeFrom(from._impl_.waypoints_);
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_current_lat = from._internal_current_lat();
  uint32_t raw_current_lat;
  memcpy(&raw_current_lat, &tmp_current_lat, sizeof(tmp_current_lat));
  if (raw_current_lat != 0) {
    _this->_internal_set_current_lat(from._internal_current_lat());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_current_lon = from._internal_current_lon();
  uint32_t raw_current_lon;
  memcpy(&raw_current_lon, &tmp_current_lon, sizeof(tmp_current_lon));
  if (raw_current_lon != 0) {
    _this->_internal_set_current_lon(from._internal_current_lon());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_heading_deg = from._internal_heading_deg();
  uint32_t raw_heading_deg;
  memcpy(&raw_heading_deg, &tmp_heading_deg, sizeof(tmp_heading_deg));
  if (raw_heading_deg != 0) {
    _this->_internal_set_heading_deg(from._internal_heading_deg());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Navigation::CopyFrom(const Navigation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Navigation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Navigation::IsInitialized() const {
  return true;
}

void Navigation::InternalSwap(Navigation* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.waypoints_.InternalSwap(&other->_impl_.waypoints_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Navigation, _impl_.heading_deg_)
      + sizeof(Navigation::_impl_.heading_deg_)
      - PROTOBUF_FIELD_OFFSET(Navigation, _impl_.current_lat_)>(
          reinterpret_cast<char*>(&_impl_.current_lat_),
          reinterpret_cast<char*>(&other->_impl_.current_lat_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Navigation::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_HMI_5fRX_5fCONTROLS_2eproto_getter, &descriptor_table_HMI_5fRX_5fCONTROLS_2eproto_once,
      file_level_metadata_HMI_5fRX_5fCONTROLS_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Waypoint*
Arena::CreateMaybeMessage< ::Waypoint >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Waypoint >(arena);
}
template<> PROTOBUF_NOINLINE ::Navigation*
Arena::CreateMaybeMessage< ::Navigation >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Navigation >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
