// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HMI_TX_CONTROLS.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_HMI_5fTX_5fCONTROLS_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_HMI_5fTX_5fCONTROLS_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_HMI_5fTX_5fCONTROLS_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_HMI_5fTX_5fCONTROLS_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_HMI_5fTX_5fCONTROLS_2eproto;
class HMITxMessage;
struct HMITxMessageDefaultTypeInternal;
extern HMITxMessageDefaultTypeInternal _HMITxMessage_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::HMITxMessage* Arena::CreateMaybeMessage<::HMITxMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class HMITxMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:HMITxMessage) */ {
 public:
  inline HMITxMessage() : HMITxMessage(nullptr) {}
  ~HMITxMessage() override;
  explicit PROTOBUF_CONSTEXPR HMITxMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HMITxMessage(const HMITxMessage& from);
  HMITxMessage(HMITxMessage&& from) noexcept
    : HMITxMessage() {
    *this = ::std::move(from);
  }

  inline HMITxMessage& operator=(const HMITxMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline HMITxMessage& operator=(HMITxMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HMITxMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const HMITxMessage* internal_default_instance() {
    return reinterpret_cast<const HMITxMessage*>(
               &_HMITxMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(HMITxMessage& a, HMITxMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(HMITxMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HMITxMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HMITxMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HMITxMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HMITxMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HMITxMessage& from) {
    HMITxMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HMITxMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "HMITxMessage";
  }
  protected:
  explicit HMITxMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTargetDestinationFieldNumber = 2,
    kEngageStatusFieldNumber = 1,
  };
  // string target_destination = 2;
  void clear_target_destination();
  const std::string& target_destination() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_target_destination(ArgT0&& arg0, ArgT... args);
  std::string* mutable_target_destination();
  PROTOBUF_NODISCARD std::string* release_target_destination();
  void set_allocated_target_destination(std::string* target_destination);
  private:
  const std::string& _internal_target_destination() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_target_destination(const std::string& value);
  std::string* _internal_mutable_target_destination();
  public:

  // int32 engage_status = 1;
  void clear_engage_status();
  int32_t engage_status() const;
  void set_engage_status(int32_t value);
  private:
  int32_t _internal_engage_status() const;
  void _internal_set_engage_status(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:HMITxMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr target_destination_;
    int32_t engage_status_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HMI_5fTX_5fCONTROLS_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HMITxMessage

// int32 engage_status = 1;
inline void HMITxMessage::clear_engage_status() {
  _impl_.engage_status_ = 0;
}
inline int32_t HMITxMessage::_internal_engage_status() const {
  return _impl_.engage_status_;
}
inline int32_t HMITxMessage::engage_status() const {
  // @@protoc_insertion_point(field_get:HMITxMessage.engage_status)
  return _internal_engage_status();
}
inline void HMITxMessage::_internal_set_engage_status(int32_t value) {
  
  _impl_.engage_status_ = value;
}
inline void HMITxMessage::set_engage_status(int32_t value) {
  _internal_set_engage_status(value);
  // @@protoc_insertion_point(field_set:HMITxMessage.engage_status)
}

// string target_destination = 2;
inline void HMITxMessage::clear_target_destination() {
  _impl_.target_destination_.ClearToEmpty();
}
inline const std::string& HMITxMessage::target_destination() const {
  // @@protoc_insertion_point(field_get:HMITxMessage.target_destination)
  return _internal_target_destination();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HMITxMessage::set_target_destination(ArgT0&& arg0, ArgT... args) {
 
 _impl_.target_destination_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:HMITxMessage.target_destination)
}
inline std::string* HMITxMessage::mutable_target_destination() {
  std::string* _s = _internal_mutable_target_destination();
  // @@protoc_insertion_point(field_mutable:HMITxMessage.target_destination)
  return _s;
}
inline const std::string& HMITxMessage::_internal_target_destination() const {
  return _impl_.target_destination_.Get();
}
inline void HMITxMessage::_internal_set_target_destination(const std::string& value) {
  
  _impl_.target_destination_.Set(value, GetArenaForAllocation());
}
inline std::string* HMITxMessage::_internal_mutable_target_destination() {
  
  return _impl_.target_destination_.Mutable(GetArenaForAllocation());
}
inline std::string* HMITxMessage::release_target_destination() {
  // @@protoc_insertion_point(field_release:HMITxMessage.target_destination)
  return _impl_.target_destination_.Release();
}
inline void HMITxMessage::set_allocated_target_destination(std::string* target_destination) {
  if (target_destination != nullptr) {
    
  } else {
    
  }
  _impl_.target_destination_.SetAllocated(target_destination, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.target_destination_.IsDefault()) {
    _impl_.target_destination_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:HMITxMessage.target_destination)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_HMI_5fTX_5fCONTROLS_2eproto
