// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HMI_RX_PERCEPTION.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_HMI_5fRX_5fPERCEPTION_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_HMI_5fRX_5fPERCEPTION_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_HMI_5fRX_5fPERCEPTION_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_HMI_5fRX_5fPERCEPTION_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto;
namespace perception {
class PerceptMessage;
struct PerceptMessageDefaultTypeInternal;
extern PerceptMessageDefaultTypeInternal _PerceptMessage_default_instance_;
class SignalValue;
struct SignalValueDefaultTypeInternal;
extern SignalValueDefaultTypeInternal _SignalValue_default_instance_;
}  // namespace perception
PROTOBUF_NAMESPACE_OPEN
template<> ::perception::PerceptMessage* Arena::CreateMaybeMessage<::perception::PerceptMessage>(Arena*);
template<> ::perception::SignalValue* Arena::CreateMaybeMessage<::perception::SignalValue>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace perception {

// ===================================================================

class SignalValue final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:perception.SignalValue) */ {
 public:
  inline SignalValue() : SignalValue(nullptr) {}
  ~SignalValue() override;
  explicit PROTOBUF_CONSTEXPR SignalValue(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SignalValue(const SignalValue& from);
  SignalValue(SignalValue&& from) noexcept
    : SignalValue() {
    *this = ::std::move(from);
  }

  inline SignalValue& operator=(const SignalValue& from) {
    CopyFrom(from);
    return *this;
  }
  inline SignalValue& operator=(SignalValue&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SignalValue& default_instance() {
    return *internal_default_instance();
  }
  static inline const SignalValue* internal_default_instance() {
    return reinterpret_cast<const SignalValue*>(
               &_SignalValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SignalValue& a, SignalValue& b) {
    a.Swap(&b);
  }
  inline void Swap(SignalValue* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SignalValue* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SignalValue* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SignalValue>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SignalValue& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SignalValue& from) {
    SignalValue::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SignalValue* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "perception.SignalValue";
  }
  protected:
  explicit SignalValue(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string value = 2;
  void clear_value();
  const std::string& value() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_value(ArgT0&& arg0, ArgT... args);
  std::string* mutable_value();
  PROTOBUF_NODISCARD std::string* release_value();
  void set_allocated_value(std::string* value);
  private:
  const std::string& _internal_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_value(const std::string& value);
  std::string* _internal_mutable_value();
  public:

  // @@protoc_insertion_point(class_scope:perception.SignalValue)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HMI_5fRX_5fPERCEPTION_2eproto;
};
// -------------------------------------------------------------------

class PerceptMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:perception.PerceptMessage) */ {
 public:
  inline PerceptMessage() : PerceptMessage(nullptr) {}
  ~PerceptMessage() override;
  explicit PROTOBUF_CONSTEXPR PerceptMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PerceptMessage(const PerceptMessage& from);
  PerceptMessage(PerceptMessage&& from) noexcept
    : PerceptMessage() {
    *this = ::std::move(from);
  }

  inline PerceptMessage& operator=(const PerceptMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline PerceptMessage& operator=(PerceptMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PerceptMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const PerceptMessage* internal_default_instance() {
    return reinterpret_cast<const PerceptMessage*>(
               &_PerceptMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PerceptMessage& a, PerceptMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(PerceptMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PerceptMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PerceptMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PerceptMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PerceptMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PerceptMessage& from) {
    PerceptMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PerceptMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "perception.PerceptMessage";
  }
  protected:
  explicit PerceptMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDecodedSignalsFieldNumber = 6,
    kCategoryFieldNumber = 1,
    kMessageNameFieldNumber = 2,
    kRawDataFieldNumber = 5,
    kTimestampIso8601FieldNumber = 7,
    kCanIdFieldNumber = 3,
    kDlcFieldNumber = 4,
  };
  // repeated .perception.SignalValue decoded_signals = 6;
  int decoded_signals_size() const;
  private:
  int _internal_decoded_signals_size() const;
  public:
  void clear_decoded_signals();
  ::perception::SignalValue* mutable_decoded_signals(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::perception::SignalValue >*
      mutable_decoded_signals();
  private:
  const ::perception::SignalValue& _internal_decoded_signals(int index) const;
  ::perception::SignalValue* _internal_add_decoded_signals();
  public:
  const ::perception::SignalValue& decoded_signals(int index) const;
  ::perception::SignalValue* add_decoded_signals();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::perception::SignalValue >&
      decoded_signals() const;

  // string category = 1;
  void clear_category();
  const std::string& category() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_category(ArgT0&& arg0, ArgT... args);
  std::string* mutable_category();
  PROTOBUF_NODISCARD std::string* release_category();
  void set_allocated_category(std::string* category);
  private:
  const std::string& _internal_category() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_category(const std::string& value);
  std::string* _internal_mutable_category();
  public:

  // string message_name = 2;
  void clear_message_name();
  const std::string& message_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message_name();
  PROTOBUF_NODISCARD std::string* release_message_name();
  void set_allocated_message_name(std::string* message_name);
  private:
  const std::string& _internal_message_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message_name(const std::string& value);
  std::string* _internal_mutable_message_name();
  public:

  // bytes raw_data = 5;
  void clear_raw_data();
  const std::string& raw_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_raw_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_raw_data();
  PROTOBUF_NODISCARD std::string* release_raw_data();
  void set_allocated_raw_data(std::string* raw_data);
  private:
  const std::string& _internal_raw_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_raw_data(const std::string& value);
  std::string* _internal_mutable_raw_data();
  public:

  // string timestamp_iso8601 = 7;
  void clear_timestamp_iso8601();
  const std::string& timestamp_iso8601() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_timestamp_iso8601(ArgT0&& arg0, ArgT... args);
  std::string* mutable_timestamp_iso8601();
  PROTOBUF_NODISCARD std::string* release_timestamp_iso8601();
  void set_allocated_timestamp_iso8601(std::string* timestamp_iso8601);
  private:
  const std::string& _internal_timestamp_iso8601() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_timestamp_iso8601(const std::string& value);
  std::string* _internal_mutable_timestamp_iso8601();
  public:

  // uint32 can_id = 3;
  void clear_can_id();
  uint32_t can_id() const;
  void set_can_id(uint32_t value);
  private:
  uint32_t _internal_can_id() const;
  void _internal_set_can_id(uint32_t value);
  public:

  // uint32 dlc = 4;
  void clear_dlc();
  uint32_t dlc() const;
  void set_dlc(uint32_t value);
  private:
  uint32_t _internal_dlc() const;
  void _internal_set_dlc(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:perception.PerceptMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::perception::SignalValue > decoded_signals_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr category_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr raw_data_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr timestamp_iso8601_;
    uint32_t can_id_;
    uint32_t dlc_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HMI_5fRX_5fPERCEPTION_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SignalValue

// string name = 1;
inline void SignalValue::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& SignalValue::name() const {
  // @@protoc_insertion_point(field_get:perception.SignalValue.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SignalValue::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:perception.SignalValue.name)
}
inline std::string* SignalValue::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:perception.SignalValue.name)
  return _s;
}
inline const std::string& SignalValue::_internal_name() const {
  return _impl_.name_.Get();
}
inline void SignalValue::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* SignalValue::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* SignalValue::release_name() {
  // @@protoc_insertion_point(field_release:perception.SignalValue.name)
  return _impl_.name_.Release();
}
inline void SignalValue::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:perception.SignalValue.name)
}

// string value = 2;
inline void SignalValue::clear_value() {
  _impl_.value_.ClearToEmpty();
}
inline const std::string& SignalValue::value() const {
  // @@protoc_insertion_point(field_get:perception.SignalValue.value)
  return _internal_value();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SignalValue::set_value(ArgT0&& arg0, ArgT... args) {
 
 _impl_.value_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:perception.SignalValue.value)
}
inline std::string* SignalValue::mutable_value() {
  std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:perception.SignalValue.value)
  return _s;
}
inline const std::string& SignalValue::_internal_value() const {
  return _impl_.value_.Get();
}
inline void SignalValue::_internal_set_value(const std::string& value) {
  
  _impl_.value_.Set(value, GetArenaForAllocation());
}
inline std::string* SignalValue::_internal_mutable_value() {
  
  return _impl_.value_.Mutable(GetArenaForAllocation());
}
inline std::string* SignalValue::release_value() {
  // @@protoc_insertion_point(field_release:perception.SignalValue.value)
  return _impl_.value_.Release();
}
inline void SignalValue::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    
  } else {
    
  }
  _impl_.value_.SetAllocated(value, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:perception.SignalValue.value)
}

// -------------------------------------------------------------------

// PerceptMessage

// string category = 1;
inline void PerceptMessage::clear_category() {
  _impl_.category_.ClearToEmpty();
}
inline const std::string& PerceptMessage::category() const {
  // @@protoc_insertion_point(field_get:perception.PerceptMessage.category)
  return _internal_category();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PerceptMessage::set_category(ArgT0&& arg0, ArgT... args) {
 
 _impl_.category_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:perception.PerceptMessage.category)
}
inline std::string* PerceptMessage::mutable_category() {
  std::string* _s = _internal_mutable_category();
  // @@protoc_insertion_point(field_mutable:perception.PerceptMessage.category)
  return _s;
}
inline const std::string& PerceptMessage::_internal_category() const {
  return _impl_.category_.Get();
}
inline void PerceptMessage::_internal_set_category(const std::string& value) {
  
  _impl_.category_.Set(value, GetArenaForAllocation());
}
inline std::string* PerceptMessage::_internal_mutable_category() {
  
  return _impl_.category_.Mutable(GetArenaForAllocation());
}
inline std::string* PerceptMessage::release_category() {
  // @@protoc_insertion_point(field_release:perception.PerceptMessage.category)
  return _impl_.category_.Release();
}
inline void PerceptMessage::set_allocated_category(std::string* category) {
  if (category != nullptr) {
    
  } else {
    
  }
  _impl_.category_.SetAllocated(category, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.category_.IsDefault()) {
    _impl_.category_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:perception.PerceptMessage.category)
}

// string message_name = 2;
inline void PerceptMessage::clear_message_name() {
  _impl_.message_name_.ClearToEmpty();
}
inline const std::string& PerceptMessage::message_name() const {
  // @@protoc_insertion_point(field_get:perception.PerceptMessage.message_name)
  return _internal_message_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PerceptMessage::set_message_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:perception.PerceptMessage.message_name)
}
inline std::string* PerceptMessage::mutable_message_name() {
  std::string* _s = _internal_mutable_message_name();
  // @@protoc_insertion_point(field_mutable:perception.PerceptMessage.message_name)
  return _s;
}
inline const std::string& PerceptMessage::_internal_message_name() const {
  return _impl_.message_name_.Get();
}
inline void PerceptMessage::_internal_set_message_name(const std::string& value) {
  
  _impl_.message_name_.Set(value, GetArenaForAllocation());
}
inline std::string* PerceptMessage::_internal_mutable_message_name() {
  
  return _impl_.message_name_.Mutable(GetArenaForAllocation());
}
inline std::string* PerceptMessage::release_message_name() {
  // @@protoc_insertion_point(field_release:perception.PerceptMessage.message_name)
  return _impl_.message_name_.Release();
}
inline void PerceptMessage::set_allocated_message_name(std::string* message_name) {
  if (message_name != nullptr) {
    
  } else {
    
  }
  _impl_.message_name_.SetAllocated(message_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_name_.IsDefault()) {
    _impl_.message_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:perception.PerceptMessage.message_name)
}

// uint32 can_id = 3;
inline void PerceptMessage::clear_can_id() {
  _impl_.can_id_ = 0u;
}
inline uint32_t PerceptMessage::_internal_can_id() const {
  return _impl_.can_id_;
}
inline uint32_t PerceptMessage::can_id() const {
  // @@protoc_insertion_point(field_get:perception.PerceptMessage.can_id)
  return _internal_can_id();
}
inline void PerceptMessage::_internal_set_can_id(uint32_t value) {
  
  _impl_.can_id_ = value;
}
inline void PerceptMessage::set_can_id(uint32_t value) {
  _internal_set_can_id(value);
  // @@protoc_insertion_point(field_set:perception.PerceptMessage.can_id)
}

// uint32 dlc = 4;
inline void PerceptMessage::clear_dlc() {
  _impl_.dlc_ = 0u;
}
inline uint32_t PerceptMessage::_internal_dlc() const {
  return _impl_.dlc_;
}
inline uint32_t PerceptMessage::dlc() const {
  // @@protoc_insertion_point(field_get:perception.PerceptMessage.dlc)
  return _internal_dlc();
}
inline void PerceptMessage::_internal_set_dlc(uint32_t value) {
  
  _impl_.dlc_ = value;
}
inline void PerceptMessage::set_dlc(uint32_t value) {
  _internal_set_dlc(value);
  // @@protoc_insertion_point(field_set:perception.PerceptMessage.dlc)
}

// bytes raw_data = 5;
inline void PerceptMessage::clear_raw_data() {
  _impl_.raw_data_.ClearToEmpty();
}
inline const std::string& PerceptMessage::raw_data() const {
  // @@protoc_insertion_point(field_get:perception.PerceptMessage.raw_data)
  return _internal_raw_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PerceptMessage::set_raw_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.raw_data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:perception.PerceptMessage.raw_data)
}
inline std::string* PerceptMessage::mutable_raw_data() {
  std::string* _s = _internal_mutable_raw_data();
  // @@protoc_insertion_point(field_mutable:perception.PerceptMessage.raw_data)
  return _s;
}
inline const std::string& PerceptMessage::_internal_raw_data() const {
  return _impl_.raw_data_.Get();
}
inline void PerceptMessage::_internal_set_raw_data(const std::string& value) {
  
  _impl_.raw_data_.Set(value, GetArenaForAllocation());
}
inline std::string* PerceptMessage::_internal_mutable_raw_data() {
  
  return _impl_.raw_data_.Mutable(GetArenaForAllocation());
}
inline std::string* PerceptMessage::release_raw_data() {
  // @@protoc_insertion_point(field_release:perception.PerceptMessage.raw_data)
  return _impl_.raw_data_.Release();
}
inline void PerceptMessage::set_allocated_raw_data(std::string* raw_data) {
  if (raw_data != nullptr) {
    
  } else {
    
  }
  _impl_.raw_data_.SetAllocated(raw_data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.raw_data_.IsDefault()) {
    _impl_.raw_data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:perception.PerceptMessage.raw_data)
}

// repeated .perception.SignalValue decoded_signals = 6;
inline int PerceptMessage::_internal_decoded_signals_size() const {
  return _impl_.decoded_signals_.size();
}
inline int PerceptMessage::decoded_signals_size() const {
  return _internal_decoded_signals_size();
}
inline void PerceptMessage::clear_decoded_signals() {
  _impl_.decoded_signals_.Clear();
}
inline ::perception::SignalValue* PerceptMessage::mutable_decoded_signals(int index) {
  // @@protoc_insertion_point(field_mutable:perception.PerceptMessage.decoded_signals)
  return _impl_.decoded_signals_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::perception::SignalValue >*
PerceptMessage::mutable_decoded_signals() {
  // @@protoc_insertion_point(field_mutable_list:perception.PerceptMessage.decoded_signals)
  return &_impl_.decoded_signals_;
}
inline const ::perception::SignalValue& PerceptMessage::_internal_decoded_signals(int index) const {
  return _impl_.decoded_signals_.Get(index);
}
inline const ::perception::SignalValue& PerceptMessage::decoded_signals(int index) const {
  // @@protoc_insertion_point(field_get:perception.PerceptMessage.decoded_signals)
  return _internal_decoded_signals(index);
}
inline ::perception::SignalValue* PerceptMessage::_internal_add_decoded_signals() {
  return _impl_.decoded_signals_.Add();
}
inline ::perception::SignalValue* PerceptMessage::add_decoded_signals() {
  ::perception::SignalValue* _add = _internal_add_decoded_signals();
  // @@protoc_insertion_point(field_add:perception.PerceptMessage.decoded_signals)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::perception::SignalValue >&
PerceptMessage::decoded_signals() const {
  // @@protoc_insertion_point(field_list:perception.PerceptMessage.decoded_signals)
  return _impl_.decoded_signals_;
}

// string timestamp_iso8601 = 7;
inline void PerceptMessage::clear_timestamp_iso8601() {
  _impl_.timestamp_iso8601_.ClearToEmpty();
}
inline const std::string& PerceptMessage::timestamp_iso8601() const {
  // @@protoc_insertion_point(field_get:perception.PerceptMessage.timestamp_iso8601)
  return _internal_timestamp_iso8601();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PerceptMessage::set_timestamp_iso8601(ArgT0&& arg0, ArgT... args) {
 
 _impl_.timestamp_iso8601_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:perception.PerceptMessage.timestamp_iso8601)
}
inline std::string* PerceptMessage::mutable_timestamp_iso8601() {
  std::string* _s = _internal_mutable_timestamp_iso8601();
  // @@protoc_insertion_point(field_mutable:perception.PerceptMessage.timestamp_iso8601)
  return _s;
}
inline const std::string& PerceptMessage::_internal_timestamp_iso8601() const {
  return _impl_.timestamp_iso8601_.Get();
}
inline void PerceptMessage::_internal_set_timestamp_iso8601(const std::string& value) {
  
  _impl_.timestamp_iso8601_.Set(value, GetArenaForAllocation());
}
inline std::string* PerceptMessage::_internal_mutable_timestamp_iso8601() {
  
  return _impl_.timestamp_iso8601_.Mutable(GetArenaForAllocation());
}
inline std::string* PerceptMessage::release_timestamp_iso8601() {
  // @@protoc_insertion_point(field_release:perception.PerceptMessage.timestamp_iso8601)
  return _impl_.timestamp_iso8601_.Release();
}
inline void PerceptMessage::set_allocated_timestamp_iso8601(std::string* timestamp_iso8601) {
  if (timestamp_iso8601 != nullptr) {
    
  } else {
    
  }
  _impl_.timestamp_iso8601_.SetAllocated(timestamp_iso8601, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.timestamp_iso8601_.IsDefault()) {
    _impl_.timestamp_iso8601_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:perception.PerceptMessage.timestamp_iso8601)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace perception

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_HMI_5fRX_5fPERCEPTION_2eproto
