// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HMI_TX_CONTROLS.proto

#include "HMI_TX_CONTROLS.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR HMITxMessage::HMITxMessage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.target_destination_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.engage_status_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct HMITxMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HMITxMessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HMITxMessageDefaultTypeInternal() {}
  union {
    HMITxMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HMITxMessageDefaultTypeInternal _HMITxMessage_default_instance_;
static ::_pb::Metadata file_level_metadata_HMI_5fTX_5fCONTROLS_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_HMI_5fTX_5fCONTROLS_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_HMI_5fTX_5fCONTROLS_2eproto = nullptr;

const uint32_t TableStruct_HMI_5fTX_5fCONTROLS_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::HMITxMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::HMITxMessage, _impl_.engage_status_),
  PROTOBUF_FIELD_OFFSET(::HMITxMessage, _impl_.target_destination_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::HMITxMessage)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_HMITxMessage_default_instance_._instance,
};

const char descriptor_table_protodef_HMI_5fTX_5fCONTROLS_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025HMI_TX_CONTROLS.proto\"A\n\014HMITxMessage\022"
  "\025\n\rengage_status\030\001 \001(\005\022\032\n\022target_destina"
  "tion\030\002 \001(\tb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_HMI_5fTX_5fCONTROLS_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_HMI_5fTX_5fCONTROLS_2eproto = {
    false, false, 98, descriptor_table_protodef_HMI_5fTX_5fCONTROLS_2eproto,
    "HMI_TX_CONTROLS.proto",
    &descriptor_table_HMI_5fTX_5fCONTROLS_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_HMI_5fTX_5fCONTROLS_2eproto::offsets,
    file_level_metadata_HMI_5fTX_5fCONTROLS_2eproto, file_level_enum_descriptors_HMI_5fTX_5fCONTROLS_2eproto,
    file_level_service_descriptors_HMI_5fTX_5fCONTROLS_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_HMI_5fTX_5fCONTROLS_2eproto_getter() {
  return &descriptor_table_HMI_5fTX_5fCONTROLS_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_HMI_5fTX_5fCONTROLS_2eproto(&descriptor_table_HMI_5fTX_5fCONTROLS_2eproto);

// ===================================================================

class HMITxMessage::_Internal {
 public:
};

HMITxMessage::HMITxMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:HMITxMessage)
}
HMITxMessage::HMITxMessage(const HMITxMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  HMITxMessage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.target_destination_){}
    , decltype(_impl_.engage_status_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.target_destination_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.target_destination_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_target_destination().empty()) {
    _this->_impl_.target_destination_.Set(from._internal_target_destination(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.engage_status_ = from._impl_.engage_status_;
  // @@protoc_insertion_point(copy_constructor:HMITxMessage)
}

inline void HMITxMessage::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.target_destination_){}
    , decltype(_impl_.engage_status_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.target_destination_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.target_destination_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

HMITxMessage::~HMITxMessage() {
  // @@protoc_insertion_point(destructor:HMITxMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void HMITxMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.target_destination_.Destroy();
}

void HMITxMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void HMITxMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:HMITxMessage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.target_destination_.ClearToEmpty();
  _impl_.engage_status_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HMITxMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 engage_status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.engage_status_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string target_destination = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_target_destination();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "HMITxMessage.target_destination"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* HMITxMessage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HMITxMessage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 engage_status = 1;
  if (this->_internal_engage_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_engage_status(), target);
  }

  // string target_destination = 2;
  if (!this->_internal_target_destination().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_target_destination().data(), static_cast<int>(this->_internal_target_destination().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "HMITxMessage.target_destination");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_target_destination(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HMITxMessage)
  return target;
}

size_t HMITxMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HMITxMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string target_destination = 2;
  if (!this->_internal_target_destination().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_target_destination());
  }

  // int32 engage_status = 1;
  if (this->_internal_engage_status() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_engage_status());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HMITxMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    HMITxMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HMITxMessage::GetClassData() const { return &_class_data_; }


void HMITxMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<HMITxMessage*>(&to_msg);
  auto& from = static_cast<const HMITxMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:HMITxMessage)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_target_destination().empty()) {
    _this->_internal_set_target_destination(from._internal_target_destination());
  }
  if (from._internal_engage_status() != 0) {
    _this->_internal_set_engage_status(from._internal_engage_status());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void HMITxMessage::CopyFrom(const HMITxMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HMITxMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HMITxMessage::IsInitialized() const {
  return true;
}

void HMITxMessage::InternalSwap(HMITxMessage* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.target_destination_, lhs_arena,
      &other->_impl_.target_destination_, rhs_arena
  );
  swap(_impl_.engage_status_, other->_impl_.engage_status_);
}

::PROTOBUF_NAMESPACE_ID::Metadata HMITxMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_HMI_5fTX_5fCONTROLS_2eproto_getter, &descriptor_table_HMI_5fTX_5fCONTROLS_2eproto_once,
      file_level_metadata_HMI_5fTX_5fCONTROLS_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::HMITxMessage*
Arena::CreateMaybeMessage< ::HMITxMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HMITxMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
