// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HMI_RX_CAN.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_HMI_5fRX_5fCAN_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_HMI_5fRX_5fCAN_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_HMI_5fRX_5fCAN_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_HMI_5fRX_5fCAN_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_HMI_5fRX_5fCAN_2eproto;
namespace can_stream {
class CanBatch;
struct CanBatchDefaultTypeInternal;
extern CanBatchDefaultTypeInternal _CanBatch_default_instance_;
class CanEvent;
struct CanEventDefaultTypeInternal;
extern CanEventDefaultTypeInternal _CanEvent_default_instance_;
}  // namespace can_stream
PROTOBUF_NAMESPACE_OPEN
template<> ::can_stream::CanBatch* Arena::CreateMaybeMessage<::can_stream::CanBatch>(Arena*);
template<> ::can_stream::CanEvent* Arena::CreateMaybeMessage<::can_stream::CanEvent>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace can_stream {

// ===================================================================

class CanEvent final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:can_stream.CanEvent) */ {
 public:
  inline CanEvent() : CanEvent(nullptr) {}
  ~CanEvent() override;
  explicit PROTOBUF_CONSTEXPR CanEvent(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CanEvent(const CanEvent& from);
  CanEvent(CanEvent&& from) noexcept
    : CanEvent() {
    *this = ::std::move(from);
  }

  inline CanEvent& operator=(const CanEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline CanEvent& operator=(CanEvent&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CanEvent& default_instance() {
    return *internal_default_instance();
  }
  static inline const CanEvent* internal_default_instance() {
    return reinterpret_cast<const CanEvent*>(
               &_CanEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CanEvent& a, CanEvent& b) {
    a.Swap(&b);
  }
  inline void Swap(CanEvent* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CanEvent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CanEvent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CanEvent>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CanEvent& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CanEvent& from) {
    CanEvent::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CanEvent* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "can_stream.CanEvent";
  }
  protected:
  explicit CanEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 7,
    kBusIdFieldNumber = 1,
    kCanIdFieldNumber = 2,
    kIsExtendedFieldNumber = 3,
    kIsRtrFieldNumber = 4,
    kDlcFieldNumber = 6,
    kTsNsFieldNumber = 5,
  };
  // bytes data = 7;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // uint32 bus_id = 1;
  void clear_bus_id();
  uint32_t bus_id() const;
  void set_bus_id(uint32_t value);
  private:
  uint32_t _internal_bus_id() const;
  void _internal_set_bus_id(uint32_t value);
  public:

  // uint32 can_id = 2;
  void clear_can_id();
  uint32_t can_id() const;
  void set_can_id(uint32_t value);
  private:
  uint32_t _internal_can_id() const;
  void _internal_set_can_id(uint32_t value);
  public:

  // bool is_extended = 3;
  void clear_is_extended();
  bool is_extended() const;
  void set_is_extended(bool value);
  private:
  bool _internal_is_extended() const;
  void _internal_set_is_extended(bool value);
  public:

  // bool is_rtr = 4;
  void clear_is_rtr();
  bool is_rtr() const;
  void set_is_rtr(bool value);
  private:
  bool _internal_is_rtr() const;
  void _internal_set_is_rtr(bool value);
  public:

  // uint32 dlc = 6;
  void clear_dlc();
  uint32_t dlc() const;
  void set_dlc(uint32_t value);
  private:
  uint32_t _internal_dlc() const;
  void _internal_set_dlc(uint32_t value);
  public:

  // uint64 ts_ns = 5;
  void clear_ts_ns();
  uint64_t ts_ns() const;
  void set_ts_ns(uint64_t value);
  private:
  uint64_t _internal_ts_ns() const;
  void _internal_set_ts_ns(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:can_stream.CanEvent)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    uint32_t bus_id_;
    uint32_t can_id_;
    bool is_extended_;
    bool is_rtr_;
    uint32_t dlc_;
    uint64_t ts_ns_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HMI_5fRX_5fCAN_2eproto;
};
// -------------------------------------------------------------------

class CanBatch final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:can_stream.CanBatch) */ {
 public:
  inline CanBatch() : CanBatch(nullptr) {}
  ~CanBatch() override;
  explicit PROTOBUF_CONSTEXPR CanBatch(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CanBatch(const CanBatch& from);
  CanBatch(CanBatch&& from) noexcept
    : CanBatch() {
    *this = ::std::move(from);
  }

  inline CanBatch& operator=(const CanBatch& from) {
    CopyFrom(from);
    return *this;
  }
  inline CanBatch& operator=(CanBatch&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CanBatch& default_instance() {
    return *internal_default_instance();
  }
  static inline const CanBatch* internal_default_instance() {
    return reinterpret_cast<const CanBatch*>(
               &_CanBatch_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CanBatch& a, CanBatch& b) {
    a.Swap(&b);
  }
  inline void Swap(CanBatch* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CanBatch* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CanBatch* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CanBatch>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CanBatch& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CanBatch& from) {
    CanBatch::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CanBatch* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "can_stream.CanBatch";
  }
  protected:
  explicit CanBatch(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEventsFieldNumber = 1,
  };
  // repeated .can_stream.CanEvent events = 1;
  int events_size() const;
  private:
  int _internal_events_size() const;
  public:
  void clear_events();
  ::can_stream::CanEvent* mutable_events(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::can_stream::CanEvent >*
      mutable_events();
  private:
  const ::can_stream::CanEvent& _internal_events(int index) const;
  ::can_stream::CanEvent* _internal_add_events();
  public:
  const ::can_stream::CanEvent& events(int index) const;
  ::can_stream::CanEvent* add_events();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::can_stream::CanEvent >&
      events() const;

  // @@protoc_insertion_point(class_scope:can_stream.CanBatch)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::can_stream::CanEvent > events_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HMI_5fRX_5fCAN_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CanEvent

// uint32 bus_id = 1;
inline void CanEvent::clear_bus_id() {
  _impl_.bus_id_ = 0u;
}
inline uint32_t CanEvent::_internal_bus_id() const {
  return _impl_.bus_id_;
}
inline uint32_t CanEvent::bus_id() const {
  // @@protoc_insertion_point(field_get:can_stream.CanEvent.bus_id)
  return _internal_bus_id();
}
inline void CanEvent::_internal_set_bus_id(uint32_t value) {
  
  _impl_.bus_id_ = value;
}
inline void CanEvent::set_bus_id(uint32_t value) {
  _internal_set_bus_id(value);
  // @@protoc_insertion_point(field_set:can_stream.CanEvent.bus_id)
}

// uint32 can_id = 2;
inline void CanEvent::clear_can_id() {
  _impl_.can_id_ = 0u;
}
inline uint32_t CanEvent::_internal_can_id() const {
  return _impl_.can_id_;
}
inline uint32_t CanEvent::can_id() const {
  // @@protoc_insertion_point(field_get:can_stream.CanEvent.can_id)
  return _internal_can_id();
}
inline void CanEvent::_internal_set_can_id(uint32_t value) {
  
  _impl_.can_id_ = value;
}
inline void CanEvent::set_can_id(uint32_t value) {
  _internal_set_can_id(value);
  // @@protoc_insertion_point(field_set:can_stream.CanEvent.can_id)
}

// bool is_extended = 3;
inline void CanEvent::clear_is_extended() {
  _impl_.is_extended_ = false;
}
inline bool CanEvent::_internal_is_extended() const {
  return _impl_.is_extended_;
}
inline bool CanEvent::is_extended() const {
  // @@protoc_insertion_point(field_get:can_stream.CanEvent.is_extended)
  return _internal_is_extended();
}
inline void CanEvent::_internal_set_is_extended(bool value) {
  
  _impl_.is_extended_ = value;
}
inline void CanEvent::set_is_extended(bool value) {
  _internal_set_is_extended(value);
  // @@protoc_insertion_point(field_set:can_stream.CanEvent.is_extended)
}

// bool is_rtr = 4;
inline void CanEvent::clear_is_rtr() {
  _impl_.is_rtr_ = false;
}
inline bool CanEvent::_internal_is_rtr() const {
  return _impl_.is_rtr_;
}
inline bool CanEvent::is_rtr() const {
  // @@protoc_insertion_point(field_get:can_stream.CanEvent.is_rtr)
  return _internal_is_rtr();
}
inline void CanEvent::_internal_set_is_rtr(bool value) {
  
  _impl_.is_rtr_ = value;
}
inline void CanEvent::set_is_rtr(bool value) {
  _internal_set_is_rtr(value);
  // @@protoc_insertion_point(field_set:can_stream.CanEvent.is_rtr)
}

// uint64 ts_ns = 5;
inline void CanEvent::clear_ts_ns() {
  _impl_.ts_ns_ = uint64_t{0u};
}
inline uint64_t CanEvent::_internal_ts_ns() const {
  return _impl_.ts_ns_;
}
inline uint64_t CanEvent::ts_ns() const {
  // @@protoc_insertion_point(field_get:can_stream.CanEvent.ts_ns)
  return _internal_ts_ns();
}
inline void CanEvent::_internal_set_ts_ns(uint64_t value) {
  
  _impl_.ts_ns_ = value;
}
inline void CanEvent::set_ts_ns(uint64_t value) {
  _internal_set_ts_ns(value);
  // @@protoc_insertion_point(field_set:can_stream.CanEvent.ts_ns)
}

// uint32 dlc = 6;
inline void CanEvent::clear_dlc() {
  _impl_.dlc_ = 0u;
}
inline uint32_t CanEvent::_internal_dlc() const {
  return _impl_.dlc_;
}
inline uint32_t CanEvent::dlc() const {
  // @@protoc_insertion_point(field_get:can_stream.CanEvent.dlc)
  return _internal_dlc();
}
inline void CanEvent::_internal_set_dlc(uint32_t value) {
  
  _impl_.dlc_ = value;
}
inline void CanEvent::set_dlc(uint32_t value) {
  _internal_set_dlc(value);
  // @@protoc_insertion_point(field_set:can_stream.CanEvent.dlc)
}

// bytes data = 7;
inline void CanEvent::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& CanEvent::data() const {
  // @@protoc_insertion_point(field_get:can_stream.CanEvent.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CanEvent::set_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:can_stream.CanEvent.data)
}
inline std::string* CanEvent::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:can_stream.CanEvent.data)
  return _s;
}
inline const std::string& CanEvent::_internal_data() const {
  return _impl_.data_.Get();
}
inline void CanEvent::_internal_set_data(const std::string& value) {
  
  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* CanEvent::_internal_mutable_data() {
  
  return _impl_.data_.Mutable(GetArenaForAllocation());
}
inline std::string* CanEvent::release_data() {
  // @@protoc_insertion_point(field_release:can_stream.CanEvent.data)
  return _impl_.data_.Release();
}
inline void CanEvent::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  _impl_.data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:can_stream.CanEvent.data)
}

// -------------------------------------------------------------------

// CanBatch

// repeated .can_stream.CanEvent events = 1;
inline int CanBatch::_internal_events_size() const {
  return _impl_.events_.size();
}
inline int CanBatch::events_size() const {
  return _internal_events_size();
}
inline void CanBatch::clear_events() {
  _impl_.events_.Clear();
}
inline ::can_stream::CanEvent* CanBatch::mutable_events(int index) {
  // @@protoc_insertion_point(field_mutable:can_stream.CanBatch.events)
  return _impl_.events_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::can_stream::CanEvent >*
CanBatch::mutable_events() {
  // @@protoc_insertion_point(field_mutable_list:can_stream.CanBatch.events)
  return &_impl_.events_;
}
inline const ::can_stream::CanEvent& CanBatch::_internal_events(int index) const {
  return _impl_.events_.Get(index);
}
inline const ::can_stream::CanEvent& CanBatch::events(int index) const {
  // @@protoc_insertion_point(field_get:can_stream.CanBatch.events)
  return _internal_events(index);
}
inline ::can_stream::CanEvent* CanBatch::_internal_add_events() {
  return _impl_.events_.Add();
}
inline ::can_stream::CanEvent* CanBatch::add_events() {
  ::can_stream::CanEvent* _add = _internal_add_events();
  // @@protoc_insertion_point(field_add:can_stream.CanBatch.events)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::can_stream::CanEvent >&
CanBatch::events() const {
  // @@protoc_insertion_point(field_list:can_stream.CanBatch.events)
  return _impl_.events_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace can_stream

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_HMI_5fRX_5fCAN_2eproto
