// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HMI_RX_CAN.proto

#include "HMI_RX_CAN.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace can_stream {
PROTOBUF_CONSTEXPR CanEvent::CanEvent(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.bus_id_)*/0u
  , /*decltype(_impl_.can_id_)*/0u
  , /*decltype(_impl_.is_extended_)*/false
  , /*decltype(_impl_.is_rtr_)*/false
  , /*decltype(_impl_.dlc_)*/0u
  , /*decltype(_impl_.ts_ns_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CanEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CanEventDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CanEventDefaultTypeInternal() {}
  union {
    CanEvent _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CanEventDefaultTypeInternal _CanEvent_default_instance_;
PROTOBUF_CONSTEXPR CanBatch::CanBatch(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.events_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CanBatchDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CanBatchDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CanBatchDefaultTypeInternal() {}
  union {
    CanBatch _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CanBatchDefaultTypeInternal _CanBatch_default_instance_;
}  // namespace can_stream
static ::_pb::Metadata file_level_metadata_HMI_5fRX_5fCAN_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_HMI_5fRX_5fCAN_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_HMI_5fRX_5fCAN_2eproto = nullptr;

const uint32_t TableStruct_HMI_5fRX_5fCAN_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::can_stream::CanEvent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::can_stream::CanEvent, _impl_.bus_id_),
  PROTOBUF_FIELD_OFFSET(::can_stream::CanEvent, _impl_.can_id_),
  PROTOBUF_FIELD_OFFSET(::can_stream::CanEvent, _impl_.is_extended_),
  PROTOBUF_FIELD_OFFSET(::can_stream::CanEvent, _impl_.is_rtr_),
  PROTOBUF_FIELD_OFFSET(::can_stream::CanEvent, _impl_.ts_ns_),
  PROTOBUF_FIELD_OFFSET(::can_stream::CanEvent, _impl_.dlc_),
  PROTOBUF_FIELD_OFFSET(::can_stream::CanEvent, _impl_.data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::can_stream::CanBatch, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::can_stream::CanBatch, _impl_.events_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::can_stream::CanEvent)},
  { 13, -1, -1, sizeof(::can_stream::CanBatch)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::can_stream::_CanEvent_default_instance_._instance,
  &::can_stream::_CanBatch_default_instance_._instance,
};

const char descriptor_table_protodef_HMI_5fRX_5fCAN_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020HMI_RX_CAN.proto\022\ncan_stream\"y\n\010CanEve"
  "nt\022\016\n\006bus_id\030\001 \001(\r\022\016\n\006can_id\030\002 \001(\r\022\023\n\013is"
  "_extended\030\003 \001(\010\022\016\n\006is_rtr\030\004 \001(\010\022\r\n\005ts_ns"
  "\030\005 \001(\004\022\013\n\003dlc\030\006 \001(\r\022\014\n\004data\030\007 \001(\014\"0\n\010Can"
  "Batch\022$\n\006events\030\001 \003(\0132\024.can_stream.CanEv"
  "entb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_HMI_5fRX_5fCAN_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_HMI_5fRX_5fCAN_2eproto = {
    false, false, 211, descriptor_table_protodef_HMI_5fRX_5fCAN_2eproto,
    "HMI_RX_CAN.proto",
    &descriptor_table_HMI_5fRX_5fCAN_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_HMI_5fRX_5fCAN_2eproto::offsets,
    file_level_metadata_HMI_5fRX_5fCAN_2eproto, file_level_enum_descriptors_HMI_5fRX_5fCAN_2eproto,
    file_level_service_descriptors_HMI_5fRX_5fCAN_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_HMI_5fRX_5fCAN_2eproto_getter() {
  return &descriptor_table_HMI_5fRX_5fCAN_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_HMI_5fRX_5fCAN_2eproto(&descriptor_table_HMI_5fRX_5fCAN_2eproto);
namespace can_stream {

// ===================================================================

class CanEvent::_Internal {
 public:
};

CanEvent::CanEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:can_stream.CanEvent)
}
CanEvent::CanEvent(const CanEvent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CanEvent* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){}
    , decltype(_impl_.bus_id_){}
    , decltype(_impl_.can_id_){}
    , decltype(_impl_.is_extended_){}
    , decltype(_impl_.is_rtr_){}
    , decltype(_impl_.dlc_){}
    , decltype(_impl_.ts_ns_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_data().empty()) {
    _this->_impl_.data_.Set(from._internal_data(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.bus_id_, &from._impl_.bus_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.ts_ns_) -
    reinterpret_cast<char*>(&_impl_.bus_id_)) + sizeof(_impl_.ts_ns_));
  // @@protoc_insertion_point(copy_constructor:can_stream.CanEvent)
}

inline void CanEvent::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){}
    , decltype(_impl_.bus_id_){0u}
    , decltype(_impl_.can_id_){0u}
    , decltype(_impl_.is_extended_){false}
    , decltype(_impl_.is_rtr_){false}
    , decltype(_impl_.dlc_){0u}
    , decltype(_impl_.ts_ns_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CanEvent::~CanEvent() {
  // @@protoc_insertion_point(destructor:can_stream.CanEvent)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CanEvent::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.data_.Destroy();
}

void CanEvent::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CanEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:can_stream.CanEvent)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.ClearToEmpty();
  ::memset(&_impl_.bus_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.ts_ns_) -
      reinterpret_cast<char*>(&_impl_.bus_id_)) + sizeof(_impl_.ts_ns_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CanEvent::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 bus_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.bus_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 can_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.can_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool is_extended = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.is_extended_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool is_rtr = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.is_rtr_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 ts_ns = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.ts_ns_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 dlc = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.dlc_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes data = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CanEvent::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:can_stream.CanEvent)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 bus_id = 1;
  if (this->_internal_bus_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_bus_id(), target);
  }

  // uint32 can_id = 2;
  if (this->_internal_can_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_can_id(), target);
  }

  // bool is_extended = 3;
  if (this->_internal_is_extended() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_is_extended(), target);
  }

  // bool is_rtr = 4;
  if (this->_internal_is_rtr() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_is_rtr(), target);
  }

  // uint64 ts_ns = 5;
  if (this->_internal_ts_ns() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(5, this->_internal_ts_ns(), target);
  }

  // uint32 dlc = 6;
  if (this->_internal_dlc() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(6, this->_internal_dlc(), target);
  }

  // bytes data = 7;
  if (!this->_internal_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        7, this->_internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:can_stream.CanEvent)
  return target;
}

size_t CanEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:can_stream.CanEvent)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes data = 7;
  if (!this->_internal_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data());
  }

  // uint32 bus_id = 1;
  if (this->_internal_bus_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_bus_id());
  }

  // uint32 can_id = 2;
  if (this->_internal_can_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_can_id());
  }

  // bool is_extended = 3;
  if (this->_internal_is_extended() != 0) {
    total_size += 1 + 1;
  }

  // bool is_rtr = 4;
  if (this->_internal_is_rtr() != 0) {
    total_size += 1 + 1;
  }

  // uint32 dlc = 6;
  if (this->_internal_dlc() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_dlc());
  }

  // uint64 ts_ns = 5;
  if (this->_internal_ts_ns() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_ts_ns());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CanEvent::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CanEvent::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CanEvent::GetClassData() const { return &_class_data_; }


void CanEvent::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CanEvent*>(&to_msg);
  auto& from = static_cast<const CanEvent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:can_stream.CanEvent)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  if (from._internal_bus_id() != 0) {
    _this->_internal_set_bus_id(from._internal_bus_id());
  }
  if (from._internal_can_id() != 0) {
    _this->_internal_set_can_id(from._internal_can_id());
  }
  if (from._internal_is_extended() != 0) {
    _this->_internal_set_is_extended(from._internal_is_extended());
  }
  if (from._internal_is_rtr() != 0) {
    _this->_internal_set_is_rtr(from._internal_is_rtr());
  }
  if (from._internal_dlc() != 0) {
    _this->_internal_set_dlc(from._internal_dlc());
  }
  if (from._internal_ts_ns() != 0) {
    _this->_internal_set_ts_ns(from._internal_ts_ns());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CanEvent::CopyFrom(const CanEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:can_stream.CanEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CanEvent::IsInitialized() const {
  return true;
}

void CanEvent::InternalSwap(CanEvent* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.data_, lhs_arena,
      &other->_impl_.data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CanEvent, _impl_.ts_ns_)
      + sizeof(CanEvent::_impl_.ts_ns_)
      - PROTOBUF_FIELD_OFFSET(CanEvent, _impl_.bus_id_)>(
          reinterpret_cast<char*>(&_impl_.bus_id_),
          reinterpret_cast<char*>(&other->_impl_.bus_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CanEvent::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_HMI_5fRX_5fCAN_2eproto_getter, &descriptor_table_HMI_5fRX_5fCAN_2eproto_once,
      file_level_metadata_HMI_5fRX_5fCAN_2eproto[0]);
}

// ===================================================================

class CanBatch::_Internal {
 public:
};

CanBatch::CanBatch(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:can_stream.CanBatch)
}
CanBatch::CanBatch(const CanBatch& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CanBatch* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.events_){from._impl_.events_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:can_stream.CanBatch)
}

inline void CanBatch::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.events_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CanBatch::~CanBatch() {
  // @@protoc_insertion_point(destructor:can_stream.CanBatch)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CanBatch::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.events_.~RepeatedPtrField();
}

void CanBatch::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CanBatch::Clear() {
// @@protoc_insertion_point(message_clear_start:can_stream.CanBatch)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.events_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CanBatch::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .can_stream.CanEvent events = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_events(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CanBatch::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:can_stream.CanBatch)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .can_stream.CanEvent events = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_events_size()); i < n; i++) {
    const auto& repfield = this->_internal_events(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:can_stream.CanBatch)
  return target;
}

size_t CanBatch::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:can_stream.CanBatch)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .can_stream.CanEvent events = 1;
  total_size += 1UL * this->_internal_events_size();
  for (const auto& msg : this->_impl_.events_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CanBatch::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CanBatch::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CanBatch::GetClassData() const { return &_class_data_; }


void CanBatch::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CanBatch*>(&to_msg);
  auto& from = static_cast<const CanBatch&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:can_stream.CanBatch)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.events_.MergeFrom(from._impl_.events_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CanBatch::CopyFrom(const CanBatch& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:can_stream.CanBatch)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CanBatch::IsInitialized() const {
  return true;
}

void CanBatch::InternalSwap(CanBatch* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.events_.InternalSwap(&other->_impl_.events_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CanBatch::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_HMI_5fRX_5fCAN_2eproto_getter, &descriptor_table_HMI_5fRX_5fCAN_2eproto_once,
      file_level_metadata_HMI_5fRX_5fCAN_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace can_stream
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::can_stream::CanEvent*
Arena::CreateMaybeMessage< ::can_stream::CanEvent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::can_stream::CanEvent >(arena);
}
template<> PROTOBUF_NOINLINE ::can_stream::CanBatch*
Arena::CreateMaybeMessage< ::can_stream::CanBatch >(Arena* arena) {
  return Arena::CreateMessageInternal< ::can_stream::CanBatch >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
