// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HMI_RX_PERCEPTION.proto

#include "HMI_RX_PERCEPTION.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace perception {
PROTOBUF_CONSTEXPR SignalValue::SignalValue(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.value_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SignalValueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SignalValueDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SignalValueDefaultTypeInternal() {}
  union {
    SignalValue _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SignalValueDefaultTypeInternal _SignalValue_default_instance_;
PROTOBUF_CONSTEXPR PerceptMessage::PerceptMessage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.decoded_signals_)*/{}
  , /*decltype(_impl_.category_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.message_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.raw_data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.timestamp_iso8601_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.can_id_)*/0u
  , /*decltype(_impl_.dlc_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PerceptMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PerceptMessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PerceptMessageDefaultTypeInternal() {}
  union {
    PerceptMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PerceptMessageDefaultTypeInternal _PerceptMessage_default_instance_;
}  // namespace perception
static ::_pb::Metadata file_level_metadata_HMI_5fRX_5fPERCEPTION_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_HMI_5fRX_5fPERCEPTION_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_HMI_5fRX_5fPERCEPTION_2eproto = nullptr;

const uint32_t TableStruct_HMI_5fRX_5fPERCEPTION_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::perception::SignalValue, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::perception::SignalValue, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::perception::SignalValue, _impl_.value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::perception::PerceptMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::perception::PerceptMessage, _impl_.category_),
  PROTOBUF_FIELD_OFFSET(::perception::PerceptMessage, _impl_.message_name_),
  PROTOBUF_FIELD_OFFSET(::perception::PerceptMessage, _impl_.can_id_),
  PROTOBUF_FIELD_OFFSET(::perception::PerceptMessage, _impl_.dlc_),
  PROTOBUF_FIELD_OFFSET(::perception::PerceptMessage, _impl_.raw_data_),
  PROTOBUF_FIELD_OFFSET(::perception::PerceptMessage, _impl_.decoded_signals_),
  PROTOBUF_FIELD_OFFSET(::perception::PerceptMessage, _impl_.timestamp_iso8601_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::perception::SignalValue)},
  { 8, -1, -1, sizeof(::perception::PerceptMessage)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::perception::_SignalValue_default_instance_._instance,
  &::perception::_PerceptMessage_default_instance_._instance,
};

const char descriptor_table_protodef_HMI_5fRX_5fPERCEPTION_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027HMI_RX_PERCEPTION.proto\022\nperception\"*\n"
  "\013SignalValue\022\014\n\004name\030\001 \001(\t\022\r\n\005value\030\002 \001("
  "\t\"\264\001\n\016PerceptMessage\022\020\n\010category\030\001 \001(\t\022\024"
  "\n\014message_name\030\002 \001(\t\022\016\n\006can_id\030\003 \001(\r\022\013\n\003"
  "dlc\030\004 \001(\r\022\020\n\010raw_data\030\005 \001(\014\0220\n\017decoded_s"
  "ignals\030\006 \003(\0132\027.perception.SignalValue\022\031\n"
  "\021timestamp_iso8601\030\007 \001(\tb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto = {
    false, false, 272, descriptor_table_protodef_HMI_5fRX_5fPERCEPTION_2eproto,
    "HMI_RX_PERCEPTION.proto",
    &descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_HMI_5fRX_5fPERCEPTION_2eproto::offsets,
    file_level_metadata_HMI_5fRX_5fPERCEPTION_2eproto, file_level_enum_descriptors_HMI_5fRX_5fPERCEPTION_2eproto,
    file_level_service_descriptors_HMI_5fRX_5fPERCEPTION_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto_getter() {
  return &descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_HMI_5fRX_5fPERCEPTION_2eproto(&descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto);
namespace perception {

// ===================================================================

class SignalValue::_Internal {
 public:
};

SignalValue::SignalValue(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:perception.SignalValue)
}
SignalValue::SignalValue(const SignalValue& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SignalValue* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.value_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_value().empty()) {
    _this->_impl_.value_.Set(from._internal_value(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:perception.SignalValue)
}

inline void SignalValue::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.value_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SignalValue::~SignalValue() {
  // @@protoc_insertion_point(destructor:perception.SignalValue)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SignalValue::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
  _impl_.value_.Destroy();
}

void SignalValue::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SignalValue::Clear() {
// @@protoc_insertion_point(message_clear_start:perception.SignalValue)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.value_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SignalValue::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "perception.SignalValue.name"));
        } else
          goto handle_unusual;
        continue;
      // string value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_value();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "perception.SignalValue.value"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SignalValue::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:perception.SignalValue)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "perception.SignalValue.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // string value = 2;
  if (!this->_internal_value().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_value().data(), static_cast<int>(this->_internal_value().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "perception.SignalValue.value");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:perception.SignalValue)
  return target;
}

size_t SignalValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:perception.SignalValue)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string value = 2;
  if (!this->_internal_value().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SignalValue::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SignalValue::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SignalValue::GetClassData() const { return &_class_data_; }


void SignalValue::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SignalValue*>(&to_msg);
  auto& from = static_cast<const SignalValue&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:perception.SignalValue)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SignalValue::CopyFrom(const SignalValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:perception.SignalValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SignalValue::IsInitialized() const {
  return true;
}

void SignalValue::InternalSwap(SignalValue* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.value_, lhs_arena,
      &other->_impl_.value_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata SignalValue::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto_getter, &descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto_once,
      file_level_metadata_HMI_5fRX_5fPERCEPTION_2eproto[0]);
}

// ===================================================================

class PerceptMessage::_Internal {
 public:
};

PerceptMessage::PerceptMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:perception.PerceptMessage)
}
PerceptMessage::PerceptMessage(const PerceptMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PerceptMessage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.decoded_signals_){from._impl_.decoded_signals_}
    , decltype(_impl_.category_){}
    , decltype(_impl_.message_name_){}
    , decltype(_impl_.raw_data_){}
    , decltype(_impl_.timestamp_iso8601_){}
    , decltype(_impl_.can_id_){}
    , decltype(_impl_.dlc_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.category_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.category_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_category().empty()) {
    _this->_impl_.category_.Set(from._internal_category(), 
      _this->GetArenaForAllocation());
  }
  _impl_.message_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message_name().empty()) {
    _this->_impl_.message_name_.Set(from._internal_message_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.raw_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.raw_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_raw_data().empty()) {
    _this->_impl_.raw_data_.Set(from._internal_raw_data(), 
      _this->GetArenaForAllocation());
  }
  _impl_.timestamp_iso8601_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.timestamp_iso8601_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_timestamp_iso8601().empty()) {
    _this->_impl_.timestamp_iso8601_.Set(from._internal_timestamp_iso8601(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.can_id_, &from._impl_.can_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.dlc_) -
    reinterpret_cast<char*>(&_impl_.can_id_)) + sizeof(_impl_.dlc_));
  // @@protoc_insertion_point(copy_constructor:perception.PerceptMessage)
}

inline void PerceptMessage::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.decoded_signals_){arena}
    , decltype(_impl_.category_){}
    , decltype(_impl_.message_name_){}
    , decltype(_impl_.raw_data_){}
    , decltype(_impl_.timestamp_iso8601_){}
    , decltype(_impl_.can_id_){0u}
    , decltype(_impl_.dlc_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.category_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.category_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.message_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.raw_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.raw_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.timestamp_iso8601_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.timestamp_iso8601_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PerceptMessage::~PerceptMessage() {
  // @@protoc_insertion_point(destructor:perception.PerceptMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PerceptMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.decoded_signals_.~RepeatedPtrField();
  _impl_.category_.Destroy();
  _impl_.message_name_.Destroy();
  _impl_.raw_data_.Destroy();
  _impl_.timestamp_iso8601_.Destroy();
}

void PerceptMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PerceptMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:perception.PerceptMessage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.decoded_signals_.Clear();
  _impl_.category_.ClearToEmpty();
  _impl_.message_name_.ClearToEmpty();
  _impl_.raw_data_.ClearToEmpty();
  _impl_.timestamp_iso8601_.ClearToEmpty();
  ::memset(&_impl_.can_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.dlc_) -
      reinterpret_cast<char*>(&_impl_.can_id_)) + sizeof(_impl_.dlc_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PerceptMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string category = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_category();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "perception.PerceptMessage.category"));
        } else
          goto handle_unusual;
        continue;
      // string message_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "perception.PerceptMessage.message_name"));
        } else
          goto handle_unusual;
        continue;
      // uint32 can_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.can_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 dlc = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.dlc_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes raw_data = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_raw_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .perception.SignalValue decoded_signals = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_decoded_signals(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else
          goto handle_unusual;
        continue;
      // string timestamp_iso8601 = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_timestamp_iso8601();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "perception.PerceptMessage.timestamp_iso8601"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PerceptMessage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:perception.PerceptMessage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string category = 1;
  if (!this->_internal_category().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_category().data(), static_cast<int>(this->_internal_category().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "perception.PerceptMessage.category");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_category(), target);
  }

  // string message_name = 2;
  if (!this->_internal_message_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message_name().data(), static_cast<int>(this->_internal_message_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "perception.PerceptMessage.message_name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message_name(), target);
  }

  // uint32 can_id = 3;
  if (this->_internal_can_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_can_id(), target);
  }

  // uint32 dlc = 4;
  if (this->_internal_dlc() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_dlc(), target);
  }

  // bytes raw_data = 5;
  if (!this->_internal_raw_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        5, this->_internal_raw_data(), target);
  }

  // repeated .perception.SignalValue decoded_signals = 6;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_decoded_signals_size()); i < n; i++) {
    const auto& repfield = this->_internal_decoded_signals(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(6, repfield, repfield.GetCachedSize(), target, stream);
  }

  // string timestamp_iso8601 = 7;
  if (!this->_internal_timestamp_iso8601().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_timestamp_iso8601().data(), static_cast<int>(this->_internal_timestamp_iso8601().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "perception.PerceptMessage.timestamp_iso8601");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_timestamp_iso8601(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:perception.PerceptMessage)
  return target;
}

size_t PerceptMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:perception.PerceptMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .perception.SignalValue decoded_signals = 6;
  total_size += 1UL * this->_internal_decoded_signals_size();
  for (const auto& msg : this->_impl_.decoded_signals_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string category = 1;
  if (!this->_internal_category().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_category());
  }

  // string message_name = 2;
  if (!this->_internal_message_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message_name());
  }

  // bytes raw_data = 5;
  if (!this->_internal_raw_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_raw_data());
  }

  // string timestamp_iso8601 = 7;
  if (!this->_internal_timestamp_iso8601().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_timestamp_iso8601());
  }

  // uint32 can_id = 3;
  if (this->_internal_can_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_can_id());
  }

  // uint32 dlc = 4;
  if (this->_internal_dlc() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_dlc());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PerceptMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PerceptMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PerceptMessage::GetClassData() const { return &_class_data_; }


void PerceptMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PerceptMessage*>(&to_msg);
  auto& from = static_cast<const PerceptMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:perception.PerceptMessage)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.decoded_signals_.MergeFrom(from._impl_.decoded_signals_);
  if (!from._internal_category().empty()) {
    _this->_internal_set_category(from._internal_category());
  }
  if (!from._internal_message_name().empty()) {
    _this->_internal_set_message_name(from._internal_message_name());
  }
  if (!from._internal_raw_data().empty()) {
    _this->_internal_set_raw_data(from._internal_raw_data());
  }
  if (!from._internal_timestamp_iso8601().empty()) {
    _this->_internal_set_timestamp_iso8601(from._internal_timestamp_iso8601());
  }
  if (from._internal_can_id() != 0) {
    _this->_internal_set_can_id(from._internal_can_id());
  }
  if (from._internal_dlc() != 0) {
    _this->_internal_set_dlc(from._internal_dlc());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PerceptMessage::CopyFrom(const PerceptMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:perception.PerceptMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PerceptMessage::IsInitialized() const {
  return true;
}

void PerceptMessage::InternalSwap(PerceptMessage* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.decoded_signals_.InternalSwap(&other->_impl_.decoded_signals_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.category_, lhs_arena,
      &other->_impl_.category_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_name_, lhs_arena,
      &other->_impl_.message_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.raw_data_, lhs_arena,
      &other->_impl_.raw_data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.timestamp_iso8601_, lhs_arena,
      &other->_impl_.timestamp_iso8601_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PerceptMessage, _impl_.dlc_)
      + sizeof(PerceptMessage::_impl_.dlc_)
      - PROTOBUF_FIELD_OFFSET(PerceptMessage, _impl_.can_id_)>(
          reinterpret_cast<char*>(&_impl_.can_id_),
          reinterpret_cast<char*>(&other->_impl_.can_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PerceptMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto_getter, &descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto_once,
      file_level_metadata_HMI_5fRX_5fPERCEPTION_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace perception
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::perception::SignalValue*
Arena::CreateMaybeMessage< ::perception::SignalValue >(Arena* arena) {
  return Arena::CreateMessageInternal< ::perception::SignalValue >(arena);
}
template<> PROTOBUF_NOINLINE ::perception::PerceptMessage*
Arena::CreateMaybeMessage< ::perception::PerceptMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::perception::PerceptMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
