// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HMI_RX_CONTROLS.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_HMI_5fRX_5fCONTROLS_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_HMI_5fRX_5fCONTROLS_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_HMI_5fRX_5fCONTROLS_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_HMI_5fRX_5fCONTROLS_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_HMI_5fRX_5fCONTROLS_2eproto;
class Navigation;
struct NavigationDefaultTypeInternal;
extern NavigationDefaultTypeInternal _Navigation_default_instance_;
class Waypoint;
struct WaypointDefaultTypeInternal;
extern WaypointDefaultTypeInternal _Waypoint_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Navigation* Arena::CreateMaybeMessage<::Navigation>(Arena*);
template<> ::Waypoint* Arena::CreateMaybeMessage<::Waypoint>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Waypoint final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Waypoint) */ {
 public:
  inline Waypoint() : Waypoint(nullptr) {}
  ~Waypoint() override;
  explicit PROTOBUF_CONSTEXPR Waypoint(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Waypoint(const Waypoint& from);
  Waypoint(Waypoint&& from) noexcept
    : Waypoint() {
    *this = ::std::move(from);
  }

  inline Waypoint& operator=(const Waypoint& from) {
    CopyFrom(from);
    return *this;
  }
  inline Waypoint& operator=(Waypoint&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Waypoint& default_instance() {
    return *internal_default_instance();
  }
  static inline const Waypoint* internal_default_instance() {
    return reinterpret_cast<const Waypoint*>(
               &_Waypoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Waypoint& a, Waypoint& b) {
    a.Swap(&b);
  }
  inline void Swap(Waypoint* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Waypoint* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Waypoint* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Waypoint>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Waypoint& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Waypoint& from) {
    Waypoint::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Waypoint* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Waypoint";
  }
  protected:
  explicit Waypoint(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLatFieldNumber = 1,
    kLonFieldNumber = 2,
  };
  // float lat = 1;
  void clear_lat();
  float lat() const;
  void set_lat(float value);
  private:
  float _internal_lat() const;
  void _internal_set_lat(float value);
  public:

  // float lon = 2;
  void clear_lon();
  float lon() const;
  void set_lon(float value);
  private:
  float _internal_lon() const;
  void _internal_set_lon(float value);
  public:

  // @@protoc_insertion_point(class_scope:Waypoint)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float lat_;
    float lon_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HMI_5fRX_5fCONTROLS_2eproto;
};
// -------------------------------------------------------------------

class Navigation final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Navigation) */ {
 public:
  inline Navigation() : Navigation(nullptr) {}
  ~Navigation() override;
  explicit PROTOBUF_CONSTEXPR Navigation(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Navigation(const Navigation& from);
  Navigation(Navigation&& from) noexcept
    : Navigation() {
    *this = ::std::move(from);
  }

  inline Navigation& operator=(const Navigation& from) {
    CopyFrom(from);
    return *this;
  }
  inline Navigation& operator=(Navigation&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Navigation& default_instance() {
    return *internal_default_instance();
  }
  static inline const Navigation* internal_default_instance() {
    return reinterpret_cast<const Navigation*>(
               &_Navigation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Navigation& a, Navigation& b) {
    a.Swap(&b);
  }
  inline void Swap(Navigation* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Navigation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Navigation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Navigation>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Navigation& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Navigation& from) {
    Navigation::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Navigation* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Navigation";
  }
  protected:
  explicit Navigation(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWaypointsFieldNumber = 4,
    kCurrentLatFieldNumber = 1,
    kCurrentLonFieldNumber = 2,
    kHeadingDegFieldNumber = 3,
  };
  // repeated .Waypoint waypoints = 4;
  int waypoints_size() const;
  private:
  int _internal_waypoints_size() const;
  public:
  void clear_waypoints();
  ::Waypoint* mutable_waypoints(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Waypoint >*
      mutable_waypoints();
  private:
  const ::Waypoint& _internal_waypoints(int index) const;
  ::Waypoint* _internal_add_waypoints();
  public:
  const ::Waypoint& waypoints(int index) const;
  ::Waypoint* add_waypoints();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Waypoint >&
      waypoints() const;

  // float current_lat = 1;
  void clear_current_lat();
  float current_lat() const;
  void set_current_lat(float value);
  private:
  float _internal_current_lat() const;
  void _internal_set_current_lat(float value);
  public:

  // float current_lon = 2;
  void clear_current_lon();
  float current_lon() const;
  void set_current_lon(float value);
  private:
  float _internal_current_lon() const;
  void _internal_set_current_lon(float value);
  public:

  // float heading_deg = 3;
  void clear_heading_deg();
  float heading_deg() const;
  void set_heading_deg(float value);
  private:
  float _internal_heading_deg() const;
  void _internal_set_heading_deg(float value);
  public:

  // @@protoc_insertion_point(class_scope:Navigation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Waypoint > waypoints_;
    float current_lat_;
    float current_lon_;
    float heading_deg_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HMI_5fRX_5fCONTROLS_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Waypoint

// float lat = 1;
inline void Waypoint::clear_lat() {
  _impl_.lat_ = 0;
}
inline float Waypoint::_internal_lat() const {
  return _impl_.lat_;
}
inline float Waypoint::lat() const {
  // @@protoc_insertion_point(field_get:Waypoint.lat)
  return _internal_lat();
}
inline void Waypoint::_internal_set_lat(float value) {
  
  _impl_.lat_ = value;
}
inline void Waypoint::set_lat(float value) {
  _internal_set_lat(value);
  // @@protoc_insertion_point(field_set:Waypoint.lat)
}

// float lon = 2;
inline void Waypoint::clear_lon() {
  _impl_.lon_ = 0;
}
inline float Waypoint::_internal_lon() const {
  return _impl_.lon_;
}
inline float Waypoint::lon() const {
  // @@protoc_insertion_point(field_get:Waypoint.lon)
  return _internal_lon();
}
inline void Waypoint::_internal_set_lon(float value) {
  
  _impl_.lon_ = value;
}
inline void Waypoint::set_lon(float value) {
  _internal_set_lon(value);
  // @@protoc_insertion_point(field_set:Waypoint.lon)
}

// -------------------------------------------------------------------

// Navigation

// float current_lat = 1;
inline void Navigation::clear_current_lat() {
  _impl_.current_lat_ = 0;
}
inline float Navigation::_internal_current_lat() const {
  return _impl_.current_lat_;
}
inline float Navigation::current_lat() const {
  // @@protoc_insertion_point(field_get:Navigation.current_lat)
  return _internal_current_lat();
}
inline void Navigation::_internal_set_current_lat(float value) {
  
  _impl_.current_lat_ = value;
}
inline void Navigation::set_current_lat(float value) {
  _internal_set_current_lat(value);
  // @@protoc_insertion_point(field_set:Navigation.current_lat)
}

// float current_lon = 2;
inline void Navigation::clear_current_lon() {
  _impl_.current_lon_ = 0;
}
inline float Navigation::_internal_current_lon() const {
  return _impl_.current_lon_;
}
inline float Navigation::current_lon() const {
  // @@protoc_insertion_point(field_get:Navigation.current_lon)
  return _internal_current_lon();
}
inline void Navigation::_internal_set_current_lon(float value) {
  
  _impl_.current_lon_ = value;
}
inline void Navigation::set_current_lon(float value) {
  _internal_set_current_lon(value);
  // @@protoc_insertion_point(field_set:Navigation.current_lon)
}

// float heading_deg = 3;
inline void Navigation::clear_heading_deg() {
  _impl_.heading_deg_ = 0;
}
inline float Navigation::_internal_heading_deg() const {
  return _impl_.heading_deg_;
}
inline float Navigation::heading_deg() const {
  // @@protoc_insertion_point(field_get:Navigation.heading_deg)
  return _internal_heading_deg();
}
inline void Navigation::_internal_set_heading_deg(float value) {
  
  _impl_.heading_deg_ = value;
}
inline void Navigation::set_heading_deg(float value) {
  _internal_set_heading_deg(value);
  // @@protoc_insertion_point(field_set:Navigation.heading_deg)
}

// repeated .Waypoint waypoints = 4;
inline int Navigation::_internal_waypoints_size() const {
  return _impl_.waypoints_.size();
}
inline int Navigation::waypoints_size() const {
  return _internal_waypoints_size();
}
inline void Navigation::clear_waypoints() {
  _impl_.waypoints_.Clear();
}
inline ::Waypoint* Navigation::mutable_waypoints(int index) {
  // @@protoc_insertion_point(field_mutable:Navigation.waypoints)
  return _impl_.waypoints_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Waypoint >*
Navigation::mutable_waypoints() {
  // @@protoc_insertion_point(field_mutable_list:Navigation.waypoints)
  return &_impl_.waypoints_;
}
inline const ::Waypoint& Navigation::_internal_waypoints(int index) const {
  return _impl_.waypoints_.Get(index);
}
inline const ::Waypoint& Navigation::waypoints(int index) const {
  // @@protoc_insertion_point(field_get:Navigation.waypoints)
  return _internal_waypoints(index);
}
inline ::Waypoint* Navigation::_internal_add_waypoints() {
  return _impl_.waypoints_.Add();
}
inline ::Waypoint* Navigation::add_waypoints() {
  ::Waypoint* _add = _internal_add_waypoints();
  // @@protoc_insertion_point(field_add:Navigation.waypoints)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Waypoint >&
Navigation::waypoints() const {
  // @@protoc_insertion_point(field_list:Navigation.waypoints)
  return _impl_.waypoints_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_HMI_5fRX_5fCONTROLS_2eproto
