// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HMI_RX_PERCEPTION.proto

#include "HMI_RX_PERCEPTION.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace hmi {
namespace perception {
namespace v1 {
PROTOBUF_CONSTEXPR CoordAbs::CoordAbs(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.latitude_)*/0
  , /*decltype(_impl_.longitude_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CoordAbsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CoordAbsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CoordAbsDefaultTypeInternal() {}
  union {
    CoordAbs _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CoordAbsDefaultTypeInternal _CoordAbs_default_instance_;
PROTOBUF_CONSTEXPR PerceptionObject::PerceptionObject(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.traffic_sign_data_)*/{}
  , /*decltype(_impl_._traffic_sign_data_cached_byte_size_)*/{0}
  , /*decltype(_impl_.coord_abs_)*/nullptr
  , /*decltype(_impl_.object_type_id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PerceptionObjectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PerceptionObjectDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PerceptionObjectDefaultTypeInternal() {}
  union {
    PerceptionObject _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PerceptionObjectDefaultTypeInternal _PerceptionObject_default_instance_;
PROTOBUF_CONSTEXPR PerceptionFrame::PerceptionFrame(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.objects_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PerceptionFrameDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PerceptionFrameDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PerceptionFrameDefaultTypeInternal() {}
  union {
    PerceptionFrame _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PerceptionFrameDefaultTypeInternal _PerceptionFrame_default_instance_;
}  // namespace v1
}  // namespace perception
}  // namespace hmi
static ::_pb::Metadata file_level_metadata_HMI_5fRX_5fPERCEPTION_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_HMI_5fRX_5fPERCEPTION_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_HMI_5fRX_5fPERCEPTION_2eproto = nullptr;

const uint32_t TableStruct_HMI_5fRX_5fPERCEPTION_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hmi::perception::v1::CoordAbs, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hmi::perception::v1::CoordAbs, _impl_.latitude_),
  PROTOBUF_FIELD_OFFSET(::hmi::perception::v1::CoordAbs, _impl_.longitude_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hmi::perception::v1::PerceptionObject, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hmi::perception::v1::PerceptionObject, _impl_.object_type_id_),
  PROTOBUF_FIELD_OFFSET(::hmi::perception::v1::PerceptionObject, _impl_.coord_abs_),
  PROTOBUF_FIELD_OFFSET(::hmi::perception::v1::PerceptionObject, _impl_.traffic_sign_data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hmi::perception::v1::PerceptionFrame, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hmi::perception::v1::PerceptionFrame, _impl_.objects_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::hmi::perception::v1::CoordAbs)},
  { 8, -1, -1, sizeof(::hmi::perception::v1::PerceptionObject)},
  { 17, -1, -1, sizeof(::hmi::perception::v1::PerceptionFrame)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::hmi::perception::v1::_CoordAbs_default_instance_._instance,
  &::hmi::perception::v1::_PerceptionObject_default_instance_._instance,
  &::hmi::perception::v1::_PerceptionFrame_default_instance_._instance,
};

const char descriptor_table_protodef_HMI_5fRX_5fPERCEPTION_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027HMI_RX_PERCEPTION.proto\022\021hmi.perceptio"
  "n.v1\"/\n\010CoordAbs\022\020\n\010latitude\030\001 \001(\002\022\021\n\tlo"
  "ngitude\030\002 \001(\002\"u\n\020PerceptionObject\022\026\n\016obj"
  "ect_type_id\030\001 \001(\005\022.\n\tcoord_abs\030\002 \001(\0132\033.h"
  "mi.perception.v1.CoordAbs\022\031\n\021traffic_sig"
  "n_data\030\003 \003(\005\"G\n\017PerceptionFrame\0224\n\007objec"
  "ts\030\001 \003(\0132#.hmi.perception.v1.PerceptionO"
  "bjectb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto = {
    false, false, 293, descriptor_table_protodef_HMI_5fRX_5fPERCEPTION_2eproto,
    "HMI_RX_PERCEPTION.proto",
    &descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_HMI_5fRX_5fPERCEPTION_2eproto::offsets,
    file_level_metadata_HMI_5fRX_5fPERCEPTION_2eproto, file_level_enum_descriptors_HMI_5fRX_5fPERCEPTION_2eproto,
    file_level_service_descriptors_HMI_5fRX_5fPERCEPTION_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto_getter() {
  return &descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_HMI_5fRX_5fPERCEPTION_2eproto(&descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto);
namespace hmi {
namespace perception {
namespace v1 {

// ===================================================================

class CoordAbs::_Internal {
 public:
};

CoordAbs::CoordAbs(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hmi.perception.v1.CoordAbs)
}
CoordAbs::CoordAbs(const CoordAbs& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CoordAbs* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.latitude_){}
    , decltype(_impl_.longitude_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.latitude_, &from._impl_.latitude_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.longitude_) -
    reinterpret_cast<char*>(&_impl_.latitude_)) + sizeof(_impl_.longitude_));
  // @@protoc_insertion_point(copy_constructor:hmi.perception.v1.CoordAbs)
}

inline void CoordAbs::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.latitude_){0}
    , decltype(_impl_.longitude_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CoordAbs::~CoordAbs() {
  // @@protoc_insertion_point(destructor:hmi.perception.v1.CoordAbs)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CoordAbs::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CoordAbs::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CoordAbs::Clear() {
// @@protoc_insertion_point(message_clear_start:hmi.perception.v1.CoordAbs)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.latitude_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.longitude_) -
      reinterpret_cast<char*>(&_impl_.latitude_)) + sizeof(_impl_.longitude_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CoordAbs::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float latitude = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _impl_.latitude_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float longitude = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.longitude_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CoordAbs::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hmi.perception.v1.CoordAbs)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float latitude = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_latitude = this->_internal_latitude();
  uint32_t raw_latitude;
  memcpy(&raw_latitude, &tmp_latitude, sizeof(tmp_latitude));
  if (raw_latitude != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_latitude(), target);
  }

  // float longitude = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_longitude = this->_internal_longitude();
  uint32_t raw_longitude;
  memcpy(&raw_longitude, &tmp_longitude, sizeof(tmp_longitude));
  if (raw_longitude != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_longitude(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hmi.perception.v1.CoordAbs)
  return target;
}

size_t CoordAbs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hmi.perception.v1.CoordAbs)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float latitude = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_latitude = this->_internal_latitude();
  uint32_t raw_latitude;
  memcpy(&raw_latitude, &tmp_latitude, sizeof(tmp_latitude));
  if (raw_latitude != 0) {
    total_size += 1 + 4;
  }

  // float longitude = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_longitude = this->_internal_longitude();
  uint32_t raw_longitude;
  memcpy(&raw_longitude, &tmp_longitude, sizeof(tmp_longitude));
  if (raw_longitude != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CoordAbs::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CoordAbs::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CoordAbs::GetClassData() const { return &_class_data_; }


void CoordAbs::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CoordAbs*>(&to_msg);
  auto& from = static_cast<const CoordAbs&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hmi.perception.v1.CoordAbs)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_latitude = from._internal_latitude();
  uint32_t raw_latitude;
  memcpy(&raw_latitude, &tmp_latitude, sizeof(tmp_latitude));
  if (raw_latitude != 0) {
    _this->_internal_set_latitude(from._internal_latitude());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_longitude = from._internal_longitude();
  uint32_t raw_longitude;
  memcpy(&raw_longitude, &tmp_longitude, sizeof(tmp_longitude));
  if (raw_longitude != 0) {
    _this->_internal_set_longitude(from._internal_longitude());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CoordAbs::CopyFrom(const CoordAbs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hmi.perception.v1.CoordAbs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CoordAbs::IsInitialized() const {
  return true;
}

void CoordAbs::InternalSwap(CoordAbs* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CoordAbs, _impl_.longitude_)
      + sizeof(CoordAbs::_impl_.longitude_)
      - PROTOBUF_FIELD_OFFSET(CoordAbs, _impl_.latitude_)>(
          reinterpret_cast<char*>(&_impl_.latitude_),
          reinterpret_cast<char*>(&other->_impl_.latitude_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CoordAbs::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto_getter, &descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto_once,
      file_level_metadata_HMI_5fRX_5fPERCEPTION_2eproto[0]);
}

// ===================================================================

class PerceptionObject::_Internal {
 public:
  static const ::hmi::perception::v1::CoordAbs& coord_abs(const PerceptionObject* msg);
};

const ::hmi::perception::v1::CoordAbs&
PerceptionObject::_Internal::coord_abs(const PerceptionObject* msg) {
  return *msg->_impl_.coord_abs_;
}
PerceptionObject::PerceptionObject(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hmi.perception.v1.PerceptionObject)
}
PerceptionObject::PerceptionObject(const PerceptionObject& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PerceptionObject* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.traffic_sign_data_){from._impl_.traffic_sign_data_}
    , /*decltype(_impl_._traffic_sign_data_cached_byte_size_)*/{0}
    , decltype(_impl_.coord_abs_){nullptr}
    , decltype(_impl_.object_type_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_coord_abs()) {
    _this->_impl_.coord_abs_ = new ::hmi::perception::v1::CoordAbs(*from._impl_.coord_abs_);
  }
  _this->_impl_.object_type_id_ = from._impl_.object_type_id_;
  // @@protoc_insertion_point(copy_constructor:hmi.perception.v1.PerceptionObject)
}

inline void PerceptionObject::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.traffic_sign_data_){arena}
    , /*decltype(_impl_._traffic_sign_data_cached_byte_size_)*/{0}
    , decltype(_impl_.coord_abs_){nullptr}
    , decltype(_impl_.object_type_id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PerceptionObject::~PerceptionObject() {
  // @@protoc_insertion_point(destructor:hmi.perception.v1.PerceptionObject)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PerceptionObject::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.traffic_sign_data_.~RepeatedField();
  if (this != internal_default_instance()) delete _impl_.coord_abs_;
}

void PerceptionObject::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PerceptionObject::Clear() {
// @@protoc_insertion_point(message_clear_start:hmi.perception.v1.PerceptionObject)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.traffic_sign_data_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.coord_abs_ != nullptr) {
    delete _impl_.coord_abs_;
  }
  _impl_.coord_abs_ = nullptr;
  _impl_.object_type_id_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PerceptionObject::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 object_type_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.object_type_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .hmi.perception.v1.CoordAbs coord_abs = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_coord_abs(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated int32 traffic_sign_data = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_traffic_sign_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 24) {
          _internal_add_traffic_sign_data(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PerceptionObject::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hmi.perception.v1.PerceptionObject)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 object_type_id = 1;
  if (this->_internal_object_type_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_object_type_id(), target);
  }

  // .hmi.perception.v1.CoordAbs coord_abs = 2;
  if (this->_internal_has_coord_abs()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::coord_abs(this),
        _Internal::coord_abs(this).GetCachedSize(), target, stream);
  }

  // repeated int32 traffic_sign_data = 3;
  {
    int byte_size = _impl_._traffic_sign_data_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          3, _internal_traffic_sign_data(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hmi.perception.v1.PerceptionObject)
  return target;
}

size_t PerceptionObject::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hmi.perception.v1.PerceptionObject)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 traffic_sign_data = 3;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.traffic_sign_data_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._traffic_sign_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // .hmi.perception.v1.CoordAbs coord_abs = 2;
  if (this->_internal_has_coord_abs()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.coord_abs_);
  }

  // int32 object_type_id = 1;
  if (this->_internal_object_type_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_object_type_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PerceptionObject::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PerceptionObject::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PerceptionObject::GetClassData() const { return &_class_data_; }


void PerceptionObject::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PerceptionObject*>(&to_msg);
  auto& from = static_cast<const PerceptionObject&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hmi.perception.v1.PerceptionObject)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.traffic_sign_data_.MergeFrom(from._impl_.traffic_sign_data_);
  if (from._internal_has_coord_abs()) {
    _this->_internal_mutable_coord_abs()->::hmi::perception::v1::CoordAbs::MergeFrom(
        from._internal_coord_abs());
  }
  if (from._internal_object_type_id() != 0) {
    _this->_internal_set_object_type_id(from._internal_object_type_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PerceptionObject::CopyFrom(const PerceptionObject& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hmi.perception.v1.PerceptionObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PerceptionObject::IsInitialized() const {
  return true;
}

void PerceptionObject::InternalSwap(PerceptionObject* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.traffic_sign_data_.InternalSwap(&other->_impl_.traffic_sign_data_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PerceptionObject, _impl_.object_type_id_)
      + sizeof(PerceptionObject::_impl_.object_type_id_)
      - PROTOBUF_FIELD_OFFSET(PerceptionObject, _impl_.coord_abs_)>(
          reinterpret_cast<char*>(&_impl_.coord_abs_),
          reinterpret_cast<char*>(&other->_impl_.coord_abs_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PerceptionObject::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto_getter, &descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto_once,
      file_level_metadata_HMI_5fRX_5fPERCEPTION_2eproto[1]);
}

// ===================================================================

class PerceptionFrame::_Internal {
 public:
};

PerceptionFrame::PerceptionFrame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hmi.perception.v1.PerceptionFrame)
}
PerceptionFrame::PerceptionFrame(const PerceptionFrame& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PerceptionFrame* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.objects_){from._impl_.objects_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:hmi.perception.v1.PerceptionFrame)
}

inline void PerceptionFrame::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.objects_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PerceptionFrame::~PerceptionFrame() {
  // @@protoc_insertion_point(destructor:hmi.perception.v1.PerceptionFrame)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PerceptionFrame::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.objects_.~RepeatedPtrField();
}

void PerceptionFrame::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PerceptionFrame::Clear() {
// @@protoc_insertion_point(message_clear_start:hmi.perception.v1.PerceptionFrame)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.objects_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PerceptionFrame::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .hmi.perception.v1.PerceptionObject objects = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_objects(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PerceptionFrame::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hmi.perception.v1.PerceptionFrame)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .hmi.perception.v1.PerceptionObject objects = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_objects_size()); i < n; i++) {
    const auto& repfield = this->_internal_objects(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hmi.perception.v1.PerceptionFrame)
  return target;
}

size_t PerceptionFrame::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hmi.perception.v1.PerceptionFrame)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .hmi.perception.v1.PerceptionObject objects = 1;
  total_size += 1UL * this->_internal_objects_size();
  for (const auto& msg : this->_impl_.objects_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PerceptionFrame::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PerceptionFrame::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PerceptionFrame::GetClassData() const { return &_class_data_; }


void PerceptionFrame::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PerceptionFrame*>(&to_msg);
  auto& from = static_cast<const PerceptionFrame&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hmi.perception.v1.PerceptionFrame)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.objects_.MergeFrom(from._impl_.objects_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PerceptionFrame::CopyFrom(const PerceptionFrame& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hmi.perception.v1.PerceptionFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PerceptionFrame::IsInitialized() const {
  return true;
}

void PerceptionFrame::InternalSwap(PerceptionFrame* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.objects_.InternalSwap(&other->_impl_.objects_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PerceptionFrame::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto_getter, &descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto_once,
      file_level_metadata_HMI_5fRX_5fPERCEPTION_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace perception
}  // namespace hmi
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::hmi::perception::v1::CoordAbs*
Arena::CreateMaybeMessage< ::hmi::perception::v1::CoordAbs >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hmi::perception::v1::CoordAbs >(arena);
}
template<> PROTOBUF_NOINLINE ::hmi::perception::v1::PerceptionObject*
Arena::CreateMaybeMessage< ::hmi::perception::v1::PerceptionObject >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hmi::perception::v1::PerceptionObject >(arena);
}
template<> PROTOBUF_NOINLINE ::hmi::perception::v1::PerceptionFrame*
Arena::CreateMaybeMessage< ::hmi::perception::v1::PerceptionFrame >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hmi::perception::v1::PerceptionFrame >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
