// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HMI_RX_PERCEPTION.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_HMI_5fRX_5fPERCEPTION_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_HMI_5fRX_5fPERCEPTION_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_HMI_5fRX_5fPERCEPTION_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_HMI_5fRX_5fPERCEPTION_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_HMI_5fRX_5fPERCEPTION_2eproto;
namespace hmi {
namespace perception {
namespace v1 {
class CoordAbs;
struct CoordAbsDefaultTypeInternal;
extern CoordAbsDefaultTypeInternal _CoordAbs_default_instance_;
class PerceptionFrame;
struct PerceptionFrameDefaultTypeInternal;
extern PerceptionFrameDefaultTypeInternal _PerceptionFrame_default_instance_;
class PerceptionObject;
struct PerceptionObjectDefaultTypeInternal;
extern PerceptionObjectDefaultTypeInternal _PerceptionObject_default_instance_;
}  // namespace v1
}  // namespace perception
}  // namespace hmi
PROTOBUF_NAMESPACE_OPEN
template<> ::hmi::perception::v1::CoordAbs* Arena::CreateMaybeMessage<::hmi::perception::v1::CoordAbs>(Arena*);
template<> ::hmi::perception::v1::PerceptionFrame* Arena::CreateMaybeMessage<::hmi::perception::v1::PerceptionFrame>(Arena*);
template<> ::hmi::perception::v1::PerceptionObject* Arena::CreateMaybeMessage<::hmi::perception::v1::PerceptionObject>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace hmi {
namespace perception {
namespace v1 {

// ===================================================================

class CoordAbs final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hmi.perception.v1.CoordAbs) */ {
 public:
  inline CoordAbs() : CoordAbs(nullptr) {}
  ~CoordAbs() override;
  explicit PROTOBUF_CONSTEXPR CoordAbs(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CoordAbs(const CoordAbs& from);
  CoordAbs(CoordAbs&& from) noexcept
    : CoordAbs() {
    *this = ::std::move(from);
  }

  inline CoordAbs& operator=(const CoordAbs& from) {
    CopyFrom(from);
    return *this;
  }
  inline CoordAbs& operator=(CoordAbs&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CoordAbs& default_instance() {
    return *internal_default_instance();
  }
  static inline const CoordAbs* internal_default_instance() {
    return reinterpret_cast<const CoordAbs*>(
               &_CoordAbs_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CoordAbs& a, CoordAbs& b) {
    a.Swap(&b);
  }
  inline void Swap(CoordAbs* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CoordAbs* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CoordAbs* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CoordAbs>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CoordAbs& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CoordAbs& from) {
    CoordAbs::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CoordAbs* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hmi.perception.v1.CoordAbs";
  }
  protected:
  explicit CoordAbs(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLatitudeFieldNumber = 1,
    kLongitudeFieldNumber = 2,
  };
  // float latitude = 1;
  void clear_latitude();
  float latitude() const;
  void set_latitude(float value);
  private:
  float _internal_latitude() const;
  void _internal_set_latitude(float value);
  public:

  // float longitude = 2;
  void clear_longitude();
  float longitude() const;
  void set_longitude(float value);
  private:
  float _internal_longitude() const;
  void _internal_set_longitude(float value);
  public:

  // @@protoc_insertion_point(class_scope:hmi.perception.v1.CoordAbs)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float latitude_;
    float longitude_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HMI_5fRX_5fPERCEPTION_2eproto;
};
// -------------------------------------------------------------------

class PerceptionObject final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hmi.perception.v1.PerceptionObject) */ {
 public:
  inline PerceptionObject() : PerceptionObject(nullptr) {}
  ~PerceptionObject() override;
  explicit PROTOBUF_CONSTEXPR PerceptionObject(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PerceptionObject(const PerceptionObject& from);
  PerceptionObject(PerceptionObject&& from) noexcept
    : PerceptionObject() {
    *this = ::std::move(from);
  }

  inline PerceptionObject& operator=(const PerceptionObject& from) {
    CopyFrom(from);
    return *this;
  }
  inline PerceptionObject& operator=(PerceptionObject&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PerceptionObject& default_instance() {
    return *internal_default_instance();
  }
  static inline const PerceptionObject* internal_default_instance() {
    return reinterpret_cast<const PerceptionObject*>(
               &_PerceptionObject_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PerceptionObject& a, PerceptionObject& b) {
    a.Swap(&b);
  }
  inline void Swap(PerceptionObject* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PerceptionObject* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PerceptionObject* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PerceptionObject>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PerceptionObject& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PerceptionObject& from) {
    PerceptionObject::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PerceptionObject* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hmi.perception.v1.PerceptionObject";
  }
  protected:
  explicit PerceptionObject(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTrafficSignDataFieldNumber = 3,
    kCoordAbsFieldNumber = 2,
    kObjectTypeIdFieldNumber = 1,
  };
  // repeated int32 traffic_sign_data = 3;
  int traffic_sign_data_size() const;
  private:
  int _internal_traffic_sign_data_size() const;
  public:
  void clear_traffic_sign_data();
  private:
  int32_t _internal_traffic_sign_data(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_traffic_sign_data() const;
  void _internal_add_traffic_sign_data(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_traffic_sign_data();
  public:
  int32_t traffic_sign_data(int index) const;
  void set_traffic_sign_data(int index, int32_t value);
  void add_traffic_sign_data(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      traffic_sign_data() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_traffic_sign_data();

  // .hmi.perception.v1.CoordAbs coord_abs = 2;
  bool has_coord_abs() const;
  private:
  bool _internal_has_coord_abs() const;
  public:
  void clear_coord_abs();
  const ::hmi::perception::v1::CoordAbs& coord_abs() const;
  PROTOBUF_NODISCARD ::hmi::perception::v1::CoordAbs* release_coord_abs();
  ::hmi::perception::v1::CoordAbs* mutable_coord_abs();
  void set_allocated_coord_abs(::hmi::perception::v1::CoordAbs* coord_abs);
  private:
  const ::hmi::perception::v1::CoordAbs& _internal_coord_abs() const;
  ::hmi::perception::v1::CoordAbs* _internal_mutable_coord_abs();
  public:
  void unsafe_arena_set_allocated_coord_abs(
      ::hmi::perception::v1::CoordAbs* coord_abs);
  ::hmi::perception::v1::CoordAbs* unsafe_arena_release_coord_abs();

  // int32 object_type_id = 1;
  void clear_object_type_id();
  int32_t object_type_id() const;
  void set_object_type_id(int32_t value);
  private:
  int32_t _internal_object_type_id() const;
  void _internal_set_object_type_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:hmi.perception.v1.PerceptionObject)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > traffic_sign_data_;
    mutable std::atomic<int> _traffic_sign_data_cached_byte_size_;
    ::hmi::perception::v1::CoordAbs* coord_abs_;
    int32_t object_type_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HMI_5fRX_5fPERCEPTION_2eproto;
};
// -------------------------------------------------------------------

class PerceptionFrame final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hmi.perception.v1.PerceptionFrame) */ {
 public:
  inline PerceptionFrame() : PerceptionFrame(nullptr) {}
  ~PerceptionFrame() override;
  explicit PROTOBUF_CONSTEXPR PerceptionFrame(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PerceptionFrame(const PerceptionFrame& from);
  PerceptionFrame(PerceptionFrame&& from) noexcept
    : PerceptionFrame() {
    *this = ::std::move(from);
  }

  inline PerceptionFrame& operator=(const PerceptionFrame& from) {
    CopyFrom(from);
    return *this;
  }
  inline PerceptionFrame& operator=(PerceptionFrame&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PerceptionFrame& default_instance() {
    return *internal_default_instance();
  }
  static inline const PerceptionFrame* internal_default_instance() {
    return reinterpret_cast<const PerceptionFrame*>(
               &_PerceptionFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PerceptionFrame& a, PerceptionFrame& b) {
    a.Swap(&b);
  }
  inline void Swap(PerceptionFrame* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PerceptionFrame* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PerceptionFrame* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PerceptionFrame>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PerceptionFrame& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PerceptionFrame& from) {
    PerceptionFrame::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PerceptionFrame* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hmi.perception.v1.PerceptionFrame";
  }
  protected:
  explicit PerceptionFrame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectsFieldNumber = 1,
  };
  // repeated .hmi.perception.v1.PerceptionObject objects = 1;
  int objects_size() const;
  private:
  int _internal_objects_size() const;
  public:
  void clear_objects();
  ::hmi::perception::v1::PerceptionObject* mutable_objects(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::hmi::perception::v1::PerceptionObject >*
      mutable_objects();
  private:
  const ::hmi::perception::v1::PerceptionObject& _internal_objects(int index) const;
  ::hmi::perception::v1::PerceptionObject* _internal_add_objects();
  public:
  const ::hmi::perception::v1::PerceptionObject& objects(int index) const;
  ::hmi::perception::v1::PerceptionObject* add_objects();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::hmi::perception::v1::PerceptionObject >&
      objects() const;

  // @@protoc_insertion_point(class_scope:hmi.perception.v1.PerceptionFrame)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::hmi::perception::v1::PerceptionObject > objects_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HMI_5fRX_5fPERCEPTION_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CoordAbs

// float latitude = 1;
inline void CoordAbs::clear_latitude() {
  _impl_.latitude_ = 0;
}
inline float CoordAbs::_internal_latitude() const {
  return _impl_.latitude_;
}
inline float CoordAbs::latitude() const {
  // @@protoc_insertion_point(field_get:hmi.perception.v1.CoordAbs.latitude)
  return _internal_latitude();
}
inline void CoordAbs::_internal_set_latitude(float value) {
  
  _impl_.latitude_ = value;
}
inline void CoordAbs::set_latitude(float value) {
  _internal_set_latitude(value);
  // @@protoc_insertion_point(field_set:hmi.perception.v1.CoordAbs.latitude)
}

// float longitude = 2;
inline void CoordAbs::clear_longitude() {
  _impl_.longitude_ = 0;
}
inline float CoordAbs::_internal_longitude() const {
  return _impl_.longitude_;
}
inline float CoordAbs::longitude() const {
  // @@protoc_insertion_point(field_get:hmi.perception.v1.CoordAbs.longitude)
  return _internal_longitude();
}
inline void CoordAbs::_internal_set_longitude(float value) {
  
  _impl_.longitude_ = value;
}
inline void CoordAbs::set_longitude(float value) {
  _internal_set_longitude(value);
  // @@protoc_insertion_point(field_set:hmi.perception.v1.CoordAbs.longitude)
}

// -------------------------------------------------------------------

// PerceptionObject

// int32 object_type_id = 1;
inline void PerceptionObject::clear_object_type_id() {
  _impl_.object_type_id_ = 0;
}
inline int32_t PerceptionObject::_internal_object_type_id() const {
  return _impl_.object_type_id_;
}
inline int32_t PerceptionObject::object_type_id() const {
  // @@protoc_insertion_point(field_get:hmi.perception.v1.PerceptionObject.object_type_id)
  return _internal_object_type_id();
}
inline void PerceptionObject::_internal_set_object_type_id(int32_t value) {
  
  _impl_.object_type_id_ = value;
}
inline void PerceptionObject::set_object_type_id(int32_t value) {
  _internal_set_object_type_id(value);
  // @@protoc_insertion_point(field_set:hmi.perception.v1.PerceptionObject.object_type_id)
}

// .hmi.perception.v1.CoordAbs coord_abs = 2;
inline bool PerceptionObject::_internal_has_coord_abs() const {
  return this != internal_default_instance() && _impl_.coord_abs_ != nullptr;
}
inline bool PerceptionObject::has_coord_abs() const {
  return _internal_has_coord_abs();
}
inline void PerceptionObject::clear_coord_abs() {
  if (GetArenaForAllocation() == nullptr && _impl_.coord_abs_ != nullptr) {
    delete _impl_.coord_abs_;
  }
  _impl_.coord_abs_ = nullptr;
}
inline const ::hmi::perception::v1::CoordAbs& PerceptionObject::_internal_coord_abs() const {
  const ::hmi::perception::v1::CoordAbs* p = _impl_.coord_abs_;
  return p != nullptr ? *p : reinterpret_cast<const ::hmi::perception::v1::CoordAbs&>(
      ::hmi::perception::v1::_CoordAbs_default_instance_);
}
inline const ::hmi::perception::v1::CoordAbs& PerceptionObject::coord_abs() const {
  // @@protoc_insertion_point(field_get:hmi.perception.v1.PerceptionObject.coord_abs)
  return _internal_coord_abs();
}
inline void PerceptionObject::unsafe_arena_set_allocated_coord_abs(
    ::hmi::perception::v1::CoordAbs* coord_abs) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.coord_abs_);
  }
  _impl_.coord_abs_ = coord_abs;
  if (coord_abs) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:hmi.perception.v1.PerceptionObject.coord_abs)
}
inline ::hmi::perception::v1::CoordAbs* PerceptionObject::release_coord_abs() {
  
  ::hmi::perception::v1::CoordAbs* temp = _impl_.coord_abs_;
  _impl_.coord_abs_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::hmi::perception::v1::CoordAbs* PerceptionObject::unsafe_arena_release_coord_abs() {
  // @@protoc_insertion_point(field_release:hmi.perception.v1.PerceptionObject.coord_abs)
  
  ::hmi::perception::v1::CoordAbs* temp = _impl_.coord_abs_;
  _impl_.coord_abs_ = nullptr;
  return temp;
}
inline ::hmi::perception::v1::CoordAbs* PerceptionObject::_internal_mutable_coord_abs() {
  
  if (_impl_.coord_abs_ == nullptr) {
    auto* p = CreateMaybeMessage<::hmi::perception::v1::CoordAbs>(GetArenaForAllocation());
    _impl_.coord_abs_ = p;
  }
  return _impl_.coord_abs_;
}
inline ::hmi::perception::v1::CoordAbs* PerceptionObject::mutable_coord_abs() {
  ::hmi::perception::v1::CoordAbs* _msg = _internal_mutable_coord_abs();
  // @@protoc_insertion_point(field_mutable:hmi.perception.v1.PerceptionObject.coord_abs)
  return _msg;
}
inline void PerceptionObject::set_allocated_coord_abs(::hmi::perception::v1::CoordAbs* coord_abs) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.coord_abs_;
  }
  if (coord_abs) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(coord_abs);
    if (message_arena != submessage_arena) {
      coord_abs = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, coord_abs, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.coord_abs_ = coord_abs;
  // @@protoc_insertion_point(field_set_allocated:hmi.perception.v1.PerceptionObject.coord_abs)
}

// repeated int32 traffic_sign_data = 3;
inline int PerceptionObject::_internal_traffic_sign_data_size() const {
  return _impl_.traffic_sign_data_.size();
}
inline int PerceptionObject::traffic_sign_data_size() const {
  return _internal_traffic_sign_data_size();
}
inline void PerceptionObject::clear_traffic_sign_data() {
  _impl_.traffic_sign_data_.Clear();
}
inline int32_t PerceptionObject::_internal_traffic_sign_data(int index) const {
  return _impl_.traffic_sign_data_.Get(index);
}
inline int32_t PerceptionObject::traffic_sign_data(int index) const {
  // @@protoc_insertion_point(field_get:hmi.perception.v1.PerceptionObject.traffic_sign_data)
  return _internal_traffic_sign_data(index);
}
inline void PerceptionObject::set_traffic_sign_data(int index, int32_t value) {
  _impl_.traffic_sign_data_.Set(index, value);
  // @@protoc_insertion_point(field_set:hmi.perception.v1.PerceptionObject.traffic_sign_data)
}
inline void PerceptionObject::_internal_add_traffic_sign_data(int32_t value) {
  _impl_.traffic_sign_data_.Add(value);
}
inline void PerceptionObject::add_traffic_sign_data(int32_t value) {
  _internal_add_traffic_sign_data(value);
  // @@protoc_insertion_point(field_add:hmi.perception.v1.PerceptionObject.traffic_sign_data)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
PerceptionObject::_internal_traffic_sign_data() const {
  return _impl_.traffic_sign_data_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
PerceptionObject::traffic_sign_data() const {
  // @@protoc_insertion_point(field_list:hmi.perception.v1.PerceptionObject.traffic_sign_data)
  return _internal_traffic_sign_data();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
PerceptionObject::_internal_mutable_traffic_sign_data() {
  return &_impl_.traffic_sign_data_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
PerceptionObject::mutable_traffic_sign_data() {
  // @@protoc_insertion_point(field_mutable_list:hmi.perception.v1.PerceptionObject.traffic_sign_data)
  return _internal_mutable_traffic_sign_data();
}

// -------------------------------------------------------------------

// PerceptionFrame

// repeated .hmi.perception.v1.PerceptionObject objects = 1;
inline int PerceptionFrame::_internal_objects_size() const {
  return _impl_.objects_.size();
}
inline int PerceptionFrame::objects_size() const {
  return _internal_objects_size();
}
inline void PerceptionFrame::clear_objects() {
  _impl_.objects_.Clear();
}
inline ::hmi::perception::v1::PerceptionObject* PerceptionFrame::mutable_objects(int index) {
  // @@protoc_insertion_point(field_mutable:hmi.perception.v1.PerceptionFrame.objects)
  return _impl_.objects_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::hmi::perception::v1::PerceptionObject >*
PerceptionFrame::mutable_objects() {
  // @@protoc_insertion_point(field_mutable_list:hmi.perception.v1.PerceptionFrame.objects)
  return &_impl_.objects_;
}
inline const ::hmi::perception::v1::PerceptionObject& PerceptionFrame::_internal_objects(int index) const {
  return _impl_.objects_.Get(index);
}
inline const ::hmi::perception::v1::PerceptionObject& PerceptionFrame::objects(int index) const {
  // @@protoc_insertion_point(field_get:hmi.perception.v1.PerceptionFrame.objects)
  return _internal_objects(index);
}
inline ::hmi::perception::v1::PerceptionObject* PerceptionFrame::_internal_add_objects() {
  return _impl_.objects_.Add();
}
inline ::hmi::perception::v1::PerceptionObject* PerceptionFrame::add_objects() {
  ::hmi::perception::v1::PerceptionObject* _add = _internal_add_objects();
  // @@protoc_insertion_point(field_add:hmi.perception.v1.PerceptionFrame.objects)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::hmi::perception::v1::PerceptionObject >&
PerceptionFrame::objects() const {
  // @@protoc_insertion_point(field_list:hmi.perception.v1.PerceptionFrame.objects)
  return _impl_.objects_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace perception
}  // namespace hmi

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_HMI_5fRX_5fPERCEPTION_2eproto
